### ISSUE TITLE
Users need the way to specify their own wall time limits in benchmarks

### ISSUE THREAD

**Issue by eunovm** [sosy-lab/benchexec#100]
At the moment all benchmarks implicitly have the default wall time limit that is 30 seconds greater than a specified CPU time limit. Likely users need/want develop new benchmarks with explicit wall time limits. For old-style benchmarks new versions of BenchExec can issue warnings if wall time limits aren't specified.
BTW, runexec already has an option to specify wall time limits explicitly, so its direct users can use it already.

**Comment by PhilippWendler** [comment]
This makes sense and could certainly be added. So far nobody has actually requested it, so it seems to be more of a "nice to have", though. I will probably wait with this until there is somebody who would like to use it. Please comment here if you do want to use this.

There would be no need for warnings, though. The wall time limit would stay on by default and could be disabled manually if desired.

**Comment by cheshire** [comment]
I would really like to have a walltime-limit feature (as opposed to CPU time).
From informal conversations with SV-COMP participants I gather that a _lot_ of people would prefer to measure timeouts by walltime rather than CPU time. Adding this feature to Benchexec would be a first step in evaluating how much difference that would make.

This is anecdotal and not really supported, but I have talked to about eight people who would prefer wall time limit instead of CPU time limit, and I haven't seen a single person arguing in favor of CPU time limit.

**Comment by PhilippWendler** [comment]
Yes, as I said, if someone approaches me with a concrete usecase I would be willing to add this, but so far nobody has done that. Note that for evaluating the difference between the limits you can just run the benchmarks once and then analyze the results to see how they would look like if the other limit would have been applied.

Of course, if somebody sends a pull request, I would be willing to merge it.
