### ISSUE TITLE
Remove warnings logged for XYPlot while running the JS test suite

### ISSUE THREAD

**Issue by EshaanAgg** [sosy-lab/benchexec#1010]
![image](https://github.com/sosy-lab/benchexec/assets/96648934/15a3181a-9f98-4b6d-80e1-547b1c0f2009)
When running the complete JS test suite, the above warning is logged in the console due to using the `componentWillReceiveProps` lifecycle hook in the `XYPlot` component. Since we are using this component directly from the `react-vis` library, we can't update it's implementation. Maybe bumping the version of the library can fix the issue (?)

**Comment by PhilippWendler** [comment]
Yes, this is kind of a known issue. It is unclear whether react-vis is still maintained enough such that we can hope for a fix of https://github.com/uber/react-vis/issues/1084 / https://github.com/uber/react-vis/issues/1356.

We have #570 for tracking the question of what to do with react-vis, and I don't think we can anything do about the mentioned warnings besides from waiting for a new version of react-vis or replacing it with something else. So I will close this issue here, but nevertheless bringing up topics like this is appreciated!

**Comment by EshaanAgg** [comment]
Yes sir, sounds good! Thanks for the response and all the background to the issue!
