### ISSUE TITLE
TIMEOUT (true): both timeout and solved - race condition?

### ISSUE THREAD

**Issue by ssardina** [sosy-lab/benchexec#1064]
Hi,

On hundreds, thousands of runs, we found with a status **TIMEOUT (true)**:

```shell
doors_15.yml	TIMEOUT (true)	14400.386503	14401.003976911306	2538.352640	12288.234	131070
```

So the run time-out, but it was solved as well (which indeed the log shows it was solved). Is this expected or is it showing some kind of race-condition in benchexec?

See the time limit was 14400, so maybe the solver just solved it within a few microseconds after that?

**Comment by PhilippWendler** [comment]
Firstly, yes, there is always an inevitable small discrepancy between the time limit and the actual time the tool is stopped, typically a fraction of a second. This is not a problem, though, because BenchExec will always label the run as TIMEOUT if the time limit was hit, no matter how long it took the tool to terminate afterwards.

Secondly, independently of the above it can happen that the tool prints a result to stdout and still hits the time limit - either because it actually prints the result in the last few milliseconds before being stopped, or because it prints the result earlier and then continues to run until the time limit is hit. This is for example not that uncommon if a tool still writes some (potentially large) output files after printing the result. Both cases would have the same result as in your example.

In order to not loose the information that the tool-info module determined that the result of this run was `true` (in your example), BenchExec appends this after `TIMEOUT` as you see. The result is classified and counted in the same way as a `TIMEOUT`.

Btw., it can even be desired to have a longer time span between what the time limit defines and when the tool is forcefully stopped, for example to give the tool time to output (partial) result files in case of a time limit. This is why BenchExec optionally provides a soft and hard time limit.

**Comment by ssardina** [comment]
Fantastic answer @PhilippWendler , makes total sense. Indeed it is useful to have both TIMEOUT and the `true` there. And you are totally right, benchexec couldn't do anything better because the program can printout and then continue doing something else.

So all good, and there is no "bug" or issue per se, all makes sense. Thanks.
