### ISSUE TITLE
Assignment of non-sibling processors to a single task

### ISSUE THREAD

**Issue by martinjonas** [sosy-lab/benchexec#122]
Hi,

when running a tool which uses multiple cpu cores, BenchExec is assigning sibling cores to a single run even though non-sibling cores are available. Is this an intended behavior?

In particular, I have a benchmark with `<benchmark cpuCores="4" threads="1" ...>` and the output of BenchExec is

```
2016-01-21 17:07:28,707 - DEBUG - List of available CPU cores is [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23].
2016-01-21 17:07:28,709 - DEBUG - Physical packages of cores are defaultdict(<class 'list'>, {0: [0, 1, 2, 3, 4, 5, 12, 13, 14, 15, 16, 17], 1: [6, 7, 8, 9, 10, 11, 18, 19, 20, 21, 22, 23]}).
2016-01-21 17:07:28,710 - DEBUG - Siblings of cores are {0: [0, 12], 1: [1, 13], 2: [2, 14], 3: [3, 15], 4: [4, 16], 5: [5, 17], 6: [6, 18], 7: [7, 19], 8: [8, 20], 9: [9, 21], 10: [10, 22], 11: [11, 23], 12: [0, 12], 13: [1, 13], 14: [2, 14], 15: [3, 15], 16: [4, 16], 17: [5, 17], 18: [6, 18], 19: [7, 19], 20: [8, 20], 21: [9, 21], 22: [10, 22], 23: [11, 23]}.
2016-01-21 17:07:28,710 - DEBUG - Going to assign at most 1 runs per package, each one using 4 cores and blocking 4 cores on 1 packages.
2016-01-21 17:07:28,711 - DEBUG - Final core assignment: [[0, 1, 12, 13]].
```

However, cores 0 and 12 are sibling virtual cores mapped to the same physical core (and so are 1 and 13). Shouldn't BenchExec choose a core assignment [[0,1,2,3]], since cores 2 and 3 are available and not siblings of any of used cores?

If this is the case, I think the problem is caused by an assignment on the line 181 of `resources.py`, where _all_ sibling cores are assigned to be used. More reasonable behavior from my point of view would be to assign only the particular core and block all of its siblings, if there is enough of physical cores available. For example, the following change fixes the problem in my case:

``` python
if core not in cores_with_siblings:
    cores.append(core)
    cores_with_siblings.update(c for c in siblings_of_core[core] if not c in used_cores)
```

**Comment by PhilippWendler** [comment]
Yes, the current behavior is actually by design.

While it is important that two *different* tool runs should never be executed simultaneously on virtual cores of the same physical core (and benchexec ensures that), the question how the assignment of virtual cores for a *single* run should be done is not so clearly answerable.
In principle, both the current behavior and your proposal are acceptable.

One reason why we chose the current behavior is that it is more consistent with scaling, both with the number of cores per run and with the number of runs. For example, take a machine with 4 physical cores and hyper-threading. With your proposal, when scaling a run from 1-4 cores there should usually be a linear performance increase, but when scaling beyond that to 8 cores, there will be a smaller performance increase due to hyper-threading. The current form of core assignment gives a more regular performance increase when scaling from 2 to 4 to 6 to 8 cores.

Also consider what happens if the user decides to execute 2 runs in parallel with 4 cores. Obviously, now each of the runs needs to get 2 physical cores. The current benchexec behavior gives one of the two runs exactly the same set of cores as it would assign if there was no second core: `[[0,1,4,5],[2,3,6,7]]` is the assignment with 2 runs, `[[0,1,4,5]]` is the assignment with one run. With your proposal, the assignment for a run would differ depending on whether there are other parallel runs, the current strategy can completely avoid that.

Of course one can also discuss which assignment would be "better" (i.e., give better performance) for the benchmarked tool, but this can be hard to decide in general. For example, shared caches of virtual cores can increase or decrease the performance. Turbo Boost might also increase the performance if less physical cores are used. And furthermore, there exist different forms of virtual cores: Intel has "cheap" virtual cores with shared execution units, AMD has "richer" virtual cores where each virtual core has its own almost complete set of execution units (just without floating-point unit).

So if you have concrete arguments why you think stretching a run over as many physical cores as possible would be better than the current core assignment in general, even given the inconsistency this would create regarding to scaling cores per runs or number of runs, I would be interested in discussing them. Otherwise the current behavior will probably stay.

**Comment by martinjonas** [comment]
Thank you for the reply, the reasons you named make perfect sense. 

However, my problem with the current behavior is that it sometimes produces non-deterministic run times. I am benchmarking a parallel tool and with the core assignment [[0,1,12,13]] the performance depends on the way the OS scheduler assigns threads to the chosen cores -- the results depend on which threads get assigned to the same physical core. Sometimes, it made a great difference, e.g. one run took 227 seconds of cpu time, while another took 151 seconds of cpu time ([here is the table with the results](https://github.com/sosy-lab/benchexec/files/105202/results.zip), I made 6 runs with the same settings). When pairwise non-sibling cores were chosen, cpu times did not differ more than by a few seconds.

I agree that inconsistency regarding to scaling is a problem, but from my point of view, non-deterministic run times are problem as well. I would be happy if benchexec had for example an optional command line flag forcing it not to assign one tool run to more virtual cores on the same physical core. Or it could produce a warning to tell the user that more virtual cores of the same physical core were used and the run times can possibly be non-deterministic.

**Comment by PhilippWendler** [comment]
Thank you for providing your results. I noticed that for this table you have a core limit of 3, which means that with virtual cores, there is an asymmetric core assignment like `[[0, 1, 12]]`, where it is not surprising that performance can be non-deterministic. A warning for such assignments would certainly be appropriate.

I would be interested to know whether the performance is also non-deterministic if a symmetric assignment like `[[0,1,12,13]]` is used (at least more non-deterministic than with `[[0,1,2,3]]`). Would it be possible for you to try this out? This would help with deciding whether we should print a warning for any assignments that use virtual cores.

A command-line argument like `--no-hyperthreading` that disables the use of more than one virtual core per physical core would certainly be possible, too. Unfortunately, I am currently working on two other features for BenchExec, so I do not know whether I have time soon for this. You could also implement this yourself if you like to, I think it would be relatively straight-forward (adding the option in `benchexec.py`, getting it in `localexection.py` in `execute_benchmark` from `benchmark.config` and then acting in `resources.py` accordingly). If you implement this, a pull request would be welcome.

As a last option, you BIOS probably offers the possibility to disable hyper-threading completely, though of course this is often not an option (just wanted to mention it if it happens to be the easiest acceptable solution for you).

**Comment by martinjonas** [comment]
Yes, with symmetric assignment `[[0,1,12,13]]` the performance is also non-deterministic. My tool can only use 3 cores, not 4, so additional core to establish symmetry does not help. You can find the results here - [samePhysical.zip](https://github.com/sosy-lab/benchexec/files/108490/samePhysical.zip)

If you are interested, here are also results using the core asssignment `[[0,1,2,3]]` - [differentPhysical.zip](https://github.com/sosy-lab/benchexec/files/108493/differentPhysical.zip)

I hope I can implement the `--no-hyperthreading` argument myself. Thanks for instructions on which files to change. I will send you a pull request once this is done.

Unfortunatelty, disabling hyper-threading in BIOS is not an option for me, as I am not the administrator of the server I am running the benchmarks on.
