### ISSUE TITLE
table-generator: add sorting feature to columns

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/benchexec#130]
I think this feature would be really beneficial.
I know there's a FF plugin, but I (and many others) use Chrome, and existing table-sorting plugins for Chrome do not play nicely with Benchexec.

**Comment by PhilippWendler** [comment]
Note that since you added the floating header you need to click on a cell in the table body for sorting if you use a browser plugin, clicking on a cell in the table header won't work anymore, not even in Firefox. Do the existing plugins still not work with our tables even if you do this?

I do not have time to work on this, unfortunately, but if somebody sends a pull request, I would merge it. Before it is worked on this feature, however, there should be a discussion of how to design the feature, i.e., where to integrate the UI for it.
