### ISSUE TITLE
Time stamp for run execution

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/benchexec#221]
Besides the existing measures, it could be useful to add the start time for each run.

**Comment by dbeyer** [comment]
The exact location (hostname) is logged in BenchExec's output, but the exact time not.
Any reason for that?

**Comment by dbeyer** [comment]
This became urgent and important for me.

**Comment by dbeyer** [comment]
Removed milestone to make it even more urgent ;-)

**Comment by PhilippWendler** [comment]
I am working on this, but it is surprisingly difficult.

First, there are several possibilities for storing timestamps:
1. POSIX timestamp (seconds since epoch)
2. UTC time
3. local time including time-zone information

All three should be unique, even when local time changes due to daylight-savings time. Only 2. and 3. are human readable, and only 3. stores information about the system's timezone at the time of benchmarking. The latter might be useful to easily correlate timestamps in the tool output (which most tools output in local time) with the start time of the run. So I am planning to use 3.

Second, we need to choose a specific format. It should have the following features:
- defined in some common standard
- ability to express local time with time-zone information
- automatically sorted correctly if sorted lexicographically as a string
- sub-second precision (because with parallel runs or very fast runs we might start several runs per second)
- as human-readable as possible

`benchexec` currently uses `%Y-%m-%d %H:%M:%S %Z` in the `date` attribute of results, but this not compatible with any standard format and does not have sub-second precision.

Common standards are either RFC 2822 or ISO 8601. [RFC 2822](https://tools.ietf.org/html/rfc2822#section-3.3) is used for example in email headers, but it requires dates to be in `day month year` format, so this format does not fulfill the sorting requirement. This leaves ISO 8601, for which a formal grammar was defined in [RFC 3339](https://tools.ietf.org/html/rfc3339#section-5.6).

The resulting time format would be `%Y-%m-%dT%H:%M:%S.%f%z`. This is not as nicely readable as the current format because of the missing spaces and the numeric time-zone offset instead of the time-zone name, but standards compliance should be more important than human readability.

Unfortunately, it is difficult to print such a timestamp in Python.

The easiest way would be
```
datetime.datetime.now().astimezone().isoformat()
```
This fails in every Python version below Python 3.6 because `now()` returns a timestamp without time-zone information, and `astimezone()` supports that only from Python 3.6 onwards.

To add time-zone information to the object returned by `now()` we need a `datetime.tzinfo` instance, but this is an abstract class and on Python 2.7 does not provide any concrete instances of this class in the standard library. So we would have to write our own small time-zone class just for Python 2.7 as in the [example](https://docs.python.org/2/library/datetime.html#datetime.tzinfo) of the documentation (at least until we drop support for Python 2.7 in January).

An alternative is
```
time.strftime("%Y-%m-%dT%H:%M:%S.%f%z")
```
However, unfortunately the `time.strftime` of Python 2.7 does not support `%f` and fails silently by keeping the `%f` in the output. This would mean that the timestamp is invalid if we do not add a fallback, and that we would loose sub-second precision. The latter is unfortunate, because Python 2.7 does support `%f` in the `datetime.strftime` method (and in `datetime.isoformat`), just not in `time.strftime`. But for any of the `datetime` methods we would again need the `tzinfo` instance.

This is just to document the current state. I will investigate further if I find a way to print correct and full timestamps on all supported Python versions, or what would be the easiest way to have at least everything on Python 3.

**Comment by dbeyer** [comment]
Thanks a lot!

Here my opinion:
1. I also like option 3 most (local time including time-zone information).
2. I am also strongly in favor of ISO 8601, as always.
3. Since Python does not support decent time reporting, let's execute `date --iso-8601=ns` and take the result of that. That should be stable. Later, once Python supports it, let's replace by a native Python call.

**Comment by dbeyer** [comment]
Issue #525 was closed as duplicate, but the information there was forgotten to copy over to this issue.
Here is a copy:

The execution of a tool run is an event, and every event needs to come with a timestamp.
(Either start time or completion time.)

Proposal: Add appropriate tag inside the run tag.

BTW: The tag date inside result should be renamed to either startdate or enddate.
Furthermore, it is not a date, but a time, thus: starttime and endtime.
It is good to have this one, but strictly speaking, it can be computed (min, max)
from the above proposed tags inside each run.

**Comment by PhilippWendler** [comment]
Calling `date` is an interesting idea, but I would prefer a solution without an external process, because this always adds unwanted complexity because of the error handling that is necessary (we want to measure the start time as close as possible to the actual run start, so this is a critical region of the code).

I found a fallback for `datetime.datetime.now().astimezone()` that is not too bad implementation-wise and works on all version of Python 3, so we can use that on older Python versions. On Python 2 we would simply not output the start time at all (after all, support for Python 2 will be removed in a few weeks anyway, so it does not seem bad to skip new features for it).
