### ISSUE TITLE
Use Intel Cache Allocation Technology

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#227]
Some Intel Xeons support the [Cache Allocation Technology (CAT)](https://software.intel.com/en-us/articles/introduction-to-cache-allocation-technology), which allows controlling which CPU cores may use which parts of the (L3) cache. It should be possible to use this for avoiding the influence of cache performance for parallel benchmarks on the same CPU.

We should investigate whether this is indeed helpful and whether support can be added to BenchExec. There is a [tool from Intel](https://github.com/01org/intel-cmt-cat) ([documentation](https://github.com/01org/intel-cmt-cat/wiki/FAQ)) that we can use for investigation.

Support for this was also [added to Linux 4.10](https://kernelnewbies.org/Linux_4.10#head-ee17602bfd51f652da963422e401f36b5e2aa7b3) ([documentation](https://www.kernel.org/doc/Documentation/x86/intel_rdt_ui.txt), [article](https://lwn.net/Articles/694800/), [slides](https://events.linuxfoundation.org/sites/events/files/slides/cat8.pdf)). If we add support for CAT to BenchExec, we should probably use this kernel feature instead of directly accessing the CPU via its MSRs.

**Comment by PhilippWendler** [comment]
More information and references for CAT are in [this blog post](https://danluu.com/intel-cat/).

**Comment by PhilippWendler** [comment]
Since Linux 4.12, this feature also supports allocating memory bandwidth, which we should also use.

**Comment by Pac23** [comment]
@PhilippWendler interested in this for gsoc 2019 the prerequisite states it says "maybe C" would be required,i am super comfortable with python(one of the requirements),worked with C but not with hardware level C.So basically my questions is what is the level of C that would be involved.

**Comment by PhilippWendler** [comment]
Probably not too difficult. The goal is actually to have all in Python, and only if necessary use C. Soo far we managed to never need C, but I cannot guarantee it for this project idea.

**Comment by Pac23** [comment]
> Probably not too difficult. The goal is actually to have all in Python, and only if necessary use C. Soo far we managed to never need C, but I cannot guarantee it for this project idea.

So after some digging it seems lots of C would be required,also doing this in Python in my opinion would not be the most efficient or the fastest way to do it.

**Comment by miscellaneously** [comment]
Hi @PhilippWendler ,
I just went through the articles and references  you mentioned above , I found them intresting, I want to contribute to this project, can you please point out where exactly in benchexec, this feature is going to be integrated or i have to find that by myself as you have mentioned that 

> We should investigate whether this is indeed helpful and whether support can be added to BenchExec. 

Also what should I do to increase my proposal acceptance chance, any tasks or report I should create,for now I am setting up this program on machine get bit hang of it.Please point out some code/task so that I can appreciate the complexity of this task and prepare suitable and acheivable timeline for it.

Finally thanks for reading, waiting for your reply.

**Comment by kfriedberger** [comment]
Hi @miscellaneously,
Philipp is on holiday a few days, but I will try to answer your questions as far as possible.

As most of the code for managing limitations, core assignments and measurements is part of the class `runexecutor.py`, this might be a good point where new code for this feature should be added in the end.

A first step would be to update the information given in the beginning of this issue, because the statement is already two years old and none of our team has tracked the latest development for this feature aside of BenchExec. The whole feature might already be available in a current Linux kernel, maybe with some nice API, just like CGroups. You will need to collect some information and updates on this topic.

**Comment by miscellaneously** [comment]
Thnx,
I would surely do now some research on CAT and its implementation and
revert back here.

**Comment by alohamora** [comment]
Hello @kfriedberger @PhilippWendler 
I know I am pretty late in proposing for GSOC, but I am really excited about working on the benchexec tool for implementing cache allocation technology support.
I have been thoroughly reading the Reliable [Benchmarking: Requirements and Solutions](https://www.sosy-lab.org/research/pub/2019-STTT.Reliable_Benchmarking_Requirements_and_Solutions.pdf) paper and as per the results documented in section [4.4,](https://www.sosy-lab.org/research/pub/2019-STTT.Reliable_Benchmarking_Requirements_and_Solutions.pdf#page=9&zoom=100,0,777) we observed a significant impact of sharing memory bandwidth and cache.
Moreover as per the restrictions defined on the benchmarked tool in section [1.2](https://www.sosy-lab.org/research/pub/2019-STTT.Reliable_Benchmarking_Requirements_and_Solutions.pdf#page=2&zoom=100,0,777), we can fairly say that the benchmarked tool has a negligible memory reuse profile and the current memory contention schemes leads to high miss frequency for these programs.
Therefore I think that we can use CAT for benchexec to minimize the high miss frequency in parallel executions. This is also confirmed in the results documented in this [slide](https://events.static.linuxfound.org/sites/events/files/slides/cat8.pdf).
Moreover the Resource Director Technology package provides the [OS interface support](https://github.com/intel/intel-cmt-cat/blob/94376bd56f8c9e844d404349a32bc197950c8472/README#L224) for L3 CAT, L2 CAT in linux kernel 4.10 and it has also added support for memory bandwidth allocation (MBA) in kernel 4.12.
Thus we can use this kernel extension instead of using MSRs which is also documented as a preferred choice in their [documentation](https://github.com/intel/intel-cmt-cat/blob/94376bd56f8c9e844d404349a32bc197950c8472/README#L186).
Therefore, I am really excited to work on benchexec and would really like your help in building a proposal for the same.

**Comment by PhilippWendler** [comment]
@alohamora implemented what is currently possible in #446.
