### ISSUE TITLE
Feature request: LaTeX output

### ISSUE THREAD

**Issue by mdangl** [sosy-lab/benchexec#242]
Feature request:

BenchExec already has some cool output in CSV and HTML format.

As a researcher who wants to use BenchExec to enhance their paper with reproducible experiments,
I would like to directly include the output of my BenchExec results into my papers using LaTeX macros.

For example, I would like to be able to ``\include`` a file of LaTeX macros,
each of which represents one of the summary cells of the tables produced by the table generator.
There could even be different macros for different units, e.g.
a macro for time in seconds and another one for time in hours.
If there are different categories, there should be macros for individual categories and for overall.

Of course, there would have to be some smart conversion of identifiers to allowed LaTeX macro names;
LaTeX does not allow all characters for macros that are allowed for BenchExec run definitions.

**Comment by PhilippWendler** [comment]
I have added a prototype for this in 566cd8a. It outputs only statistics for number of results and CPU time, but for these, all values from the table footers are available. There are total values, values for each category (correct/incorrect/error), and for each tuple of category and status.

Conversion into different units should simply be handled inside TeX, because we cannot now upfront what units are desired, and users might want to use the same value with different units.
Macros for individual categories are not directly possible because the result XML files do not contain enough information, but users can easily work around this by running the script on each of the individual category result files that BenchExec produces.

The conversion to LaTeX macro names is easy, we can simply remove all non-letter characters and convert to camel-case to make the name easier to read.

What do you think of this?

Further open questions:
- Integrate into table-generator or keep separate?
- Can we wrap the numbers in some siunitx command automatically? The commands should stay usable in tables with `S` columns.
- Add unit to command name? (Would be easier if integrated in table-generator.)

**Comment by mdangl** [comment]
Cool!

> Integrate into table-generator or keep separate?

Yes, I think that would be beneficial. As you already said, it would be easier to have the unit feature there.
Also, it would then probably be more likely that new outputs added to the tables are also available as macros consistently.

> Can we wrap the numbers in some siunitx command automatically? The commands should stay usable in tables with S columns.

We could probably, for each value, output two macros: One wrapped, one plain.

**Comment by PhilippWendler** [comment]
>> Can we wrap the numbers in some siunitx command automatically? The commands should stay usable in tables with S columns.
> 
> We could probably, for each value, output two macros: One wrapped, one plain.

I tried defining a regular command and a starred version, but this failed in some specific use cases (like using the command inside arithmetic expressions with `\fp_eval:n`). And anything else than appending a `*` is not really more convenient than prefixing the command with `\num`. If we add units, we might reconsider providing two commands, though.

**Comment by PhilippWendler** [comment]
Recently, we had a use case where it would have been nice to have this integrated in `table-generator`, because we wanted to combine this feature with `<union>` tags in table definitions. Similarly, `<column>` definitions are currently not possible for TeX output, and not even memory results are dumped. So there are strong arguments for moving this into `table-generator` as an output format.

While doing so, we could also consider dumping the info of the benchmark environment into the TeX output, such that everything from the first tab of the HTML tables is available.

**Comment by PhilippWendler** [comment]
Pointers for implementation:
- New output-file formats can be hooked in [here](https://github.com/sosy-lab/benchexec/blob/12246550cc9a267b2b5caca345bae654692348bd/benchexec/tablegenerator/__init__.py#L1386).
- [This](https://github.com/sosy-lab/benchexec/blob/12246550cc9a267b2b5caca345bae654692348bd/benchexec/tablegenerator/__init__.py#L1171) is the calculation of the statistics that will be passed to the output method, as reference for how the data looks like.
- [Here](https://github.com/sosy-lab/benchexec/blob/12246550cc9a267b2b5caca345bae654692348bd/benchexec/tablegenerator/htmltable.py#L267) is how the HTML export uses the computed statistics values.
