### ISSUE TITLE
possible bug: invalid cross-device-link

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#257]
I can currently not reproduce this error, but I report it for documentation.
Perhaps someone wants too dig deeper and fix it :-)

I executed a big benchmark (50k tasks) via VCloud and afterwards, when the script was parsing all the results, it crashed. This happened today at 12:19 on our computer 'koblenz'.

> Traceback (most recent call last):
>  File "scripts/benchmark.py", line 138, in <module>
    benchexec.benchexec.main(Benchmark())
>  File "scripts/../lib/python-benchmark/BenchExec-1.10-py3-none-any.whl/benchexec/benchexec.py", line 339, in main
>  File "scripts/../lib/python-benchmark/BenchExec-1.10-py3-none-any.whl/benchexec/benchexec.py", line 80, in start
>  File "scripts/../lib/python-benchmark/BenchExec-1.10-py3-none-any.whl/benchexec/benchexec.py", line 264, in execute_benchmark
>  File "/$HOME$/cpachecker/scripts/benchmark/vcloud.py", line 131, in execute_benchmark
    handleCloudResults(benchmark, output_handler, usedWallTime)
>  File "/$HOME$/cpachecker/scripts/benchmark/vcloud.py", line 282, in handleCloudResults
    output_handler.output_after_run(run)
>  File "scripts/../lib/python-benchmark/BenchExec-1.10-py3-none-any.whl/benchexec/outputhandler.py", line 423, in output_after_run
>  File "scripts/../lib/python-benchmark/BenchExec-1.10-py3-none-any.whl/benchexec/filewriter.py", line 63, in append
> OSError: [Errno 18] Invalid cross-device link: 'test/results/bigtest.2017-09-12_1433.results.txt.tmp' -> 'test/results/bigtest.2017-09-12_1433.results.txt'

**Comment by PhilippWendler** [comment]
This can happen only if `test/results/bigtest.2017-09-12_1433.results.txt.tmp` is on a different partition than `test/results/bigtest.2017-09-12_1433.results.txt`. As both files are in the same directory, this is usually impossible. I suspect it happened because something changed the underlying directories while BenchExec was running (e.g., remounting them, moving them, etc.). There is nothing that BenchExec can do for this.
