### ISSUE TITLE
Optional annotation field for tool-info modules: URL for test archive

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/benchexec#343]
It might be useful for a user who wants to experiment with a tool to find out from where to obtain the actual tool.

Example use case: A user wants to execute `<tool>` with BenchExec.

Solution: Add the below annotation in file `benchexec/benchexec/tools/<tool>.py`.
```
# Download test executable: https://gitlab.com/sosy-lab/sv-comp/archives-2019/blob/master/2019/<tool>.zip
```

**Comment by PhilippWendler** [comment]
Interesting idea.

Referencing SV-COMP archives might not be ideal, because the URLs contain years and will get outdated. Furthermore, tool authors might prefer a link to their homepage.

But the latter is certainly useful as documentation, and we should encourage authors to add such information. I will add this to the readme and provide an example.

**Comment by PhilippWendler** [comment]
Done in bd82323.
