### ISSUE TITLE
Errors not reproducible

### ISSUE THREAD

**Issue by shaobo-he** [sosy-lab/benchexec#425]
Hello,

I'm using benchexec version `1.19-dev` to evaluate a tool I'm building. The log file said there is a `SIGSEGV MAPERR si_code 1 fault on addr 0x7fb65b7e7ff0`. But I cannot reproduce it using the exact the same command on the same machine. I doubt it's related to memory limit. Any suggestions are appreciated.

**Comment by PhilippWendler** [comment]
Everything that is in the log below the first few lines comes directly from the benchmarked tool, BenchExec does not affect that. So if it says SIGSEV than it seems one of your processes segfaulted. BenchExec won't be able to give you more information because it has no insight into the process(es) of your tool.

I don't fully understand what you wrote in this issue, though. Do you have a concrete question regarding BenchExec?

**Comment by shaobo-he** [comment]
Yes. Let me give an example. The following is a log of running my tool on a benchmark. The status of this run is `aborted`.

```bash
$ cat QF_FP_OPT.newton_2_1_true-unreach-call-main.smt2.log
/usr/bin/racket /proj/fmr/tools/sls/main.rkt --seed 2 --step 1000000 /proj/fmr/QF_FP_OPT/ramalho/esbmc/newton_2_1_true-unreach-call-main.smt2


--------------------------------------------------------------------------------


../../src/get_str.c:153: MPFR assertion failed: size_s1 >= m
```
When I run the command shown at the beginning of this log, I could not get any assertion failures like the log indicated. I think I set the rng seed through the command line option, so unless there are other sources of nondeterminism, I should be able to reproduce this error.

**Comment by PhilippWendler** [comment]
I understand, but what is your question?

BenchExec does not influence the benchmarked tool in any way that could crash the tool if it didn't already contain a bug that could crash it without BenchExec, too (because BenchExec just instructs the kernel to apply some restrictions for the process, but all of these restrictions could also exist on a regular system without BenchExec).

So you need to debug your tool and find out what specifically causes it to crash, in the same way you would investigate it if it crashes on machine A and not machine B: by minimizing differences between the machines and trying to find out which difference affects the tool behavior. For BenchExec, my suggestion would be to use `runexec` instead of `benchexec` (easier for trying out different configurations because no XML files need to be edited) and individually disable and enable time limit, memory limit, core limit, container mode, etc.

**Comment by shaobo-he** [comment]
Thank you for the info. I think `runexec` is what I need.
