### ISSUE TITLE
Improve closing of pop-up view windows

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/benchexec#485]
Improve user interaction for closing the view window that pops up when clicking on a task source or log link.

In the old tables, pressing ESC worked for me.

**Comment by PhilippWendler** [comment]
There is an X in the upper right corner of the overlay.

**Comment by dbeyer** [comment]
Here how it looks to me:

![Screenshot from 2019-11-02 10-20-27](https://user-images.githubusercontent.com/2941008/68068941-975f4d00-fd5a-11e9-93e9-f5d1962fb0fd.png)

**Comment by PhilippWendler** [comment]
Ok, that should be fixed. My scroll bar looks like this:
![image](https://user-images.githubusercontent.com/2545335/68068989-15bbef00-fd5b-11e9-84ca-63277a4ea234.png)

But I currently do not know how to do this, because the scroll bar is rendered by the browser and we do not know its size. The browser really should not render scroll bars on top of actual content, but let the content's positioning be relative to the inner side of the scroll bar.

**Comment by dbeyer** [comment]
I could easily live with the hidden `X`, if the ESC key would work ;-)

Any chance to activate `ESC`?

**Comment by dbeyer** [comment]
I can confirm that the `X` is not hidden when using Firefox. The screenshot was taken with Chrome. Ha! Due to the new tables, I do not need to use Chrome anymore!

**Comment by PhilippWendler** [comment]
I pushed some CSS fixes that should improve positioning of the X.

We can keep this issue open for adding a keyboard shortcut for ESC.

Related: #113

**Comment by dbeyer** [comment]
> I pushed some CSS fixes that should improve positioning of the X.

Looks good now. Thanks!
