### ISSUE TITLE
Add Option to include Non-Minified Javascript into Tables.

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#503]
For debugging problems with tables, it is easier when actually having some non-minified Javascript available at user-side. Could we add an option `--non-minified` into the table-generator to allow to include the non-minified Javascript?

**Comment by PhilippWendler** [comment]
No. The JavaScript code is not only minified, but also collected from dozens of files and transpiled into code that your browser understands. The same is true for our CSS files (which are created from Sass sources). So there simply is no non-minified version that could be included.

But this is also not necessary, because there is already a nice-to-use development environment configured in the repository:
```
cd benchexec/tablegenerator/react-table
npm start
# Without local node installation use Docker instead:
sudo docker run --network=host --expose 3000 -v $(pwd)/..:$(pwd)/.. -w $(pwd) node npm run start
xdg-open http://localhost:3000
```
This is also documented in the [README](https://github.com/sosy-lab/benchexec/blob/master/benchexec/tablegenerator/react-table/README.md).

**Comment by kfriedberger** [comment]
Thanks for the hint, I will take a look.

**Comment by PhilippWendler** [comment]
I forgot to mention: The development environment actually has several further advantages: auto-reload if any file changes (style changes are even applied immediately without reloading) and a build in development mode that shows stacktraces etc.

**Comment by PhilippWendler** [comment]
Cf. #515.
