### ISSUE TITLE
Quantile Plot is a few Pixels too high for Browser Window.

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#504]
In the newer tables like [one example from Buildbot](https://buildbot.sosy-lab.org/cpachecker/results/nightly-induction/00076.nightly-induction.diff.html), the quantile plot itself has the height of the window and additionally it has a padding-top of about 43px for the list of tabs, which is not subtracted from its size. Thus the quantile plot is too high and does not show the last line of the legend without scrolling. Is this intended? Can the CSS be changed?

The same problem does not appear for scatter plots.

**Comment by PhilippWendler** [comment]
The situation is actually different. We specify a size for the plot, and the library will render the legend below the plot, but we do not know the size of the legend and cannot account for it. So if the legend grows beyond some height, there is no space left.

There is a scroll bar, though, so you can still see everything.

The only possibility that I see right now would be to set a fixed size on the legend, but then this would mean that the legend would get a scroll bar instead of the whole window. Not sure whether this would be better (the scroll bar would be quite small).

**Comment by kfriedberger** [comment]
Ok, I see.
As this is not really an important problem, I close this issue.
