### ISSUE TITLE
Improve core assignment with multiple NUMA regions per socket

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#51]
If a machine has multiple NUMA regions per socket, BenchExec should try to distribute the runs across all NUMA regions of each socket. Currently it first uses the cores that belong to one NUMA region, then those of the second region etc.

**Comment by PhilippWendler** [comment]
This is also a problem if several runs should be executed with few cores but much memory, such that for example the cores for all runs are taken from the first NUMA region, but not enough memory is available in that region.

**Comment by alohamora** [comment]
To handle multiple nodes per socket we can alter the `cores_per_package` to `cores_per_region`  in `resources.py`.
https://github.com/sosy-lab/benchexec/blob/0775a3223d47971b7bcecbdd60edc0af6be7e4b4/benchexec/resources.py#L88
Therefore instead of finding physical packages of core, we find memory regions for each core
```
memory_regions = []
for core in allCpus:
    coreDir = '/sys/devices/system/cpu/cpu{0}/'.format(core)
    memory_regions.append(_get_memory_banks_listed_in_dir(coreDir))
``` 
And correspondingly we build a `cores_per_region` mapping instead of `cores_per_package`
https://github.com/sosy-lab/benchexec/blob/0775a3223d47971b7bcecbdd60edc0af6be7e4b4/benchexec/resources.py#L90-L91

```
for core, region in zip(allCpus, memory_regions):
    cores_of_region[region].append(core)
```
Now using `cores_per_region` shall not affect the distribution for systems with single node per socket(or package) and for systems with multiple NUMA regions the algorithm shall split the socket into different groups each with their own different NUMA region.
This shall improve core assignment as runs shall be split accross memory regions instead of packages, thus ensuring that all the memory regions are used equally.

**Comment by PhilippWendler** [comment]
Sounds good. Please make sure that the code would still work for systems that have multiple packages per NUMA node (we do not know such systems, but they could exist). In this case, actual packages should be used, of course (we will always use whatever is more fine granular: NUMA nodes or packages).
