### ISSUE TITLE
Merging results from different run sets

### ISSUE THREAD

**Issue by rafaelsamenezes** [sosy-lab/benchexec#542]
Hello,

I am running benchexec across multiple Docker containers where each container executes a specific run set (using the `--tasks` flag).  However, when using the table-generator the resulting HTML have a column for each set. Is there a way to merge it as one column?

**Comment by kfriedberger** [comment]
Concatenating several results (with distinct filenames per task) into one table is possible. Please try to use a table-definition-xml-file like [this one](https://github.com/sosy-lab/benchexec/blob/master/doc/table-generator-example.xml) and use the `union` tag that concatenates the contained results. The execute `table-generator -x XMLFILE` to create a html-table.

**Comment by rafaelsamenezes** [comment]
I was able to generate the merged table using the table-definition-xml-file. Thank you.

**Comment by shonfeder** [comment]
Sorry to revive this old issue, but I was wondering if there's any way of getting merged results from from run sets that use different options on the same tasks. 

I'm having trouble getting useful info from the current graphs, given our needs. We want to get results in a situation that is as follows:

- We have two tasks, "TaskA" and "TaskB"
- We have 4 different option configurations "Options1", "Options2", "Options3", and "Options3".
- We want to run both TaskA and TaskB with certain option configurations, producing results for
  - TaskA with Options1
  - TaskA with Options2
  - TaskB with Options3
  - TaskB with Options4

Now, we'd like to be able to compare the results of all these experiments, but, as far as I can tell, the current table generation doesn't seem to provide a way to get all of these results on the same scatter plots.

We can of course produce our own plots using the data from the results, but I'm trying to delegate as much as I can to benchexec, since the implementation is so solid and well thought out, and I'm trying to reduce the amount of ad hoc logic I introduce into our benchmarking :) (Many thanks for developing and maintaining such a great tool, btw!)

**Comment by PhilippWendler** [comment]
Good idea to post this on the old issue, this way the explanations for all this will be in the same place. And thanks for the nice feedback!

Indeed, what you are asking is possible with the following ([doc](https://github.com/sosy-lab/benchexec/blob/bbf9bc961023b1ccbf4d4645db14b7c8af006456/doc/table-generator.xml#L46-L50)):
```xml
<union>
  <result id="options1" filename="*taskA.options1.results*"/>
  <result id="options2" filename="*taskA.options2.results*"/>
  <result id="options3" filename="*taskB.options3.results*"/>
  <result id="options4" filename="*taskB.options4.results*"/>
</union>
```
The `filename` needs the correct file names (or patterns), of course. The strings given for `id` will be visible in the left-most column of the HTML table and added as another column in the CSV. You can pick whatever you want for these ids, they just need to ensure uniqueness over the task set (i.e., no tasks with same name and same result id).

**Comment by shonfeder** [comment]
Perfect! We're getting all the results on the same scatter plot now. Thanks very much for the help. With this example in hand, the documentation makes perfect sense to me. But I couldn't quite puzzle out the details without it.

I have one further question on this point:

In an experiment where we are running 4 different tasks and combining their results using union, the generated table gives fairly inscruitable lists for the `Run set` and `options` fields on the summary now. E.g., 

![image](https://user-images.githubusercontent.com/19820422/156101246-ce6ecbd5-80c1-4d85-9fce-21e3145cd514.png)

The data is all correct, of course, it's just not very easy to work out which "Run set" title corresponds to which set of options (and it will get more difficult as the number of tasks increase). Afaict, there's no other place on the generated tables that provide an easy way to identify which runs correlate with which option sets.  Do you know of an easy config change I could make to help with this aspect of the report?

**Comment by PhilippWendler** [comment]
There is no config change for this, unfortunately, it needs to be implemented. I have created a sepearate issue for this.
