### ISSUE TITLE
Add Support for the new reach_error-Function of SV-Benchmarks

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#546]
With https://github.com/sosy-lab/sv-benchmarks/pull/1078, there is a new and not backwards-compatible error-function in the property files of SV-Benchmarks.
This new function seems to not yet be supported by BenchExec.

Please add support and then update the BenchExec version in CPAchecker.

**Comment by PhilippWendler** [comment]
Why do you claim that "this function seems not yet be supported by BenchExec"? BenchExec does not know anything about "error functions" and never did. And since version 1.17 there is no need anymore to hard-code all known property files.

**Comment by kfriedberger** [comment]
Several parts of BenchExec depends on the exact String `__VERIFIER_error`,
otherwise this String would not appear in the code.
The following locations should be adapted to the new error-function, shouldn't they?

<pre>
benchexec/tools/civl.py: if any("__VERIFIER_error() is called." in s for s in output):
benchexec/tools/tbf.py: " and always checks for calls to __VERIFIER_error()"
</pre>
For tool-wrappers, someone can of course assume, they were written for the last sv-comp/test-comp and do not need to support newer versions of sv-benchmarks.

<pre>
benchexec/result.py: "LTL(G ! call(__VERIFIER_error()))": _PROP_CALL,
</pre>
`_PROP_CALL` seems to used in several places. Is it important?

<pre>
doc/properties/unreach-call.prp: CHECK( init(main()), LTL(G ! call(__VERIFIER_error())) )
</pre>
This documentation seems to be outdated now.

**Comment by PhilippWendler** [comment]
> Several parts of BenchExec depends on the exact String `__VERIFIER_error`,
> otherwise this String would not appear in the code.
> The following locations should be adapted to the new error-function, shouldn't they?
>
> ```
> benchexec/tools/civl.py: if any("__VERIFIER_error() is called." in s for s in output):
> benchexec/tools/tbf.py: " and always checks for calls to __VERIFIER_error()"
> ```

For tool-info modules, the respective authors are responsible. We do not even know what happens if some arbitrary new property file is given to the tool.

> ```
> benchexec/result.py: "LTL(G ! call(__VERIFIER_error()))": _PROP_CALL,
> ```
>
> `_PROP_CALL` seems to used in several places. Is it important?

Only for tasks defined without task-definition files, and there won't be any support for new properties for these kind of tasks. In fact, we are removing most of that code in #439 and potentially everything in #508.

> ```
> doc/properties/unreach-call.prp: CHECK( init(main()), LTL(G ! call(__VERIFIER_error())) )
> ```
>
> This documentation seems to be outdated now.

The [documentation](https://github.com/sosy-lab/benchexec/blob/master/doc/properties/INDEX.md) makes it clear that these are the properties that are supported without task-definition files, and this has not changed.
