### ISSUE TITLE
Quantile Plot crashes for Columns with Space in Title

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#584]
Some BuildBot tables from BenchExec 3.0 ([table1](https://buildbot.sosy-lab.org/cpachecker/results/nightly-predicate/00148.nightly-predicate.diff.html#/quantile?column=model%20enumeration) and [table2](https://buildbot.sosy-lab.org/cpachecker/results/nightly-predicate/00148.-r34233_integration-nightly-predicate.2020-07-05_22-00-21.results.html#/quantile?column=model%20enumeration)) crash with an exception when showing the quantile plot for a column `model enumeration`. <s>The reason is probably an empty cell, i.e., missing values.</s>

The stacktrace is not very informative:
<pre>
TypeError: Cannot read property 'isVisible' of undefined
at n.value (00148.nightly-predicate.diff.html:39)
at new n (00148.nightly-predicate.diff.html:39)
...
</pre>

PS: I really like the feature of hash routing. We can directly link to crashing sites.

**Comment by PhilippWendler** [comment]
I can reproduce this with the current master. I suspect that the empty table cells are not the problem, because the plot can still not be shown if a filter for non-empty cells (`:`) is added to the respective column.

My guess would be the space in the display title of the column, because exactly those columns that have a space show the problem for me.

For easy testing, the following command line can be used (after running `npm run build`):
```
table-generator https://buildbot.sosy-lab.org/cpachecker/results/nightly-predicate/00148.-r34233_integration-nightly-predicate.2020-07-05_22-00-21.results.xml.bz2
```

**Comment by lachnerm** [comment]
Yes, this problem is directly related to columns whose display title contains whitespaces. The error appears because the parameters for the URL are not escaped before being set and therefore the parameters can contain whitespaces - which obviously isn't supported by URLs.
There are 3 solutions I can think of right now:

- We encode and decode the parameters centrally in the function that sets/gets the parameters to/from the URL with the native `encodeURIComponent` and `decodeURIComponent` functions. This is by far the easiest and safest solution, however **all** parts of the parameters will be escaped this way. This means, especially regarding the current changes about hidden columns in the URL, that for example those parameters `...table?hidden0=0,1,5,7,2,3,4` turn into `...table?hidden0=0%2C1%2C5%2C7%2C2%2C3%2C4`, which reduces the readability of URLs. This will escape all characters except for `A-Z a-z 0-9 - _ . ! ~ * ' ( )` 
- We also encode and decode the parameters like in the first approach, but we do it manually with only escaping those characters we want to escape - e.g. in this case whitespaces. This is however more prone to errors and we might run intro trouble in the future again if there are other characters in the display title that don't work well with URLs. This would however break if columns have a display title that contains exactly the sequence the characters will be escaped into (which I guess is very unlikely, as the characters are escaped into sequences like `%20`).
- We encode only the display title of columns before setting them in the URL and respectively only decode those again. With the current setup this would need to be done in every component every time the URL's parameters are accessed, because the function setting/getting the URL params doesn't know about the content. This is pretty much guaranteed to make us run into trouble later on, so I wouldn't suggest it.

In case we can be sure that there won't be any display titles containing unexpected characters, I would suggest solution 2 with manually escaping the characters `& ,` and whitespaces, as those should be the only ones that could be problematic that I can think of right now.

**Comment by PhilippWendler** [comment]
Solution 2 should avoid the problem if we also escape `%`, because then it is guaranteed that there are no collisions.

But for Solution 3, is it really that bad? Couldn't we do it only where display titles are handled, and whenever a different parameter is handled, the value is just passed through unchanged? Or will it be automatically decoded?

For Solution 1, would it be possible to keep some characters like `,` unescaped? Then this would be good solution, because I agree with this being the easiest and safest solution.

**Comment by lachnerm** [comment]
Yes, there is actually a `encodeURI` and `decodeURI` function, that can be used on the whole URL before setting/after retrieving instead of only the parameters. Using those functions, all special characters except `, / ? : @ & = + $ #` that are also escaped/unescaped by their respective `Component` function will be escaped/unescaped. I've tried it and it seems to work fine - all `,` characters are unescaped while the whitespaces are correctly escaped. Using those 2 functions for solution 1 would be the best way to go I think.

**Comment by PhilippWendler** [comment]
Sounds good!
