### ISSUE TITLE
Problem with installing benchexec 2.7-1 on Ubuntu 20.04

### ISSUE THREAD

**Issue by matthewbdwyer** [sosy-lab/benchexec#586]
I followed the instructions for installing benchexec, then added the my id to cgroups, rebooted, and ran "python3 -m benchexec.check_cgroups".  I got the following messages:

WARNING: Task was in cgroup /sys/fs/cgroup/cpu,cpuacct/system.slice/benchexec-cgroup.service for subsystem cpuacct, which is not the expected sub-cgroup of /sys/fs/cgroup/cpu,cpuacct/system.slice/benchexec-cgroup.service. Maybe some other program is interfering with cgroup management?
WARNING: Task was in cgroup /sys/fs/cgroup/cpuset/system.slice/benchexec-cgroup.service for subsystem cpuset, which is not the expected sub-cgroup of /sys/fs/cgroup/cpuset/system.slice/benchexec-cgroup.service. Maybe some other program is interfering with cgroup management?
WARNING: Task was in cgroup /sys/fs/cgroup/memory/system.slice/benchexec-cgroup.service for subsystem memory, which is not the expected sub-cgroup of /sys/fs/cgroup/memory/system.slice/benchexec-cgroup.service. Maybe some other program is interfering with cgroup management?
WARNING: Task was in cgroup /sys/fs/cgroup/freezer/system.slice/benchexec-cgroup.service for subsystem freezer, which is not the expected sub-cgroup of /sys/fs/cgroup/freezer/system.slice/benchexec-cgroup.service. Maybe some other program is interfering with cgroup management?

I did not see these under 18.04.  

Thanks

Matt

**Comment by PhilippWendler** [comment]
Thanks for reporting this!

I guess you did not use BenchExec 2.7 under the old Ubuntu? The problem is related to the former instead of the newer Ubuntu version.

Anyway, it is only a problem that invalid warnings are printed from `check_cgroups` due to a bug in the latter, BenchExec should be working fine if the actual task execution works as expected. And a fix is committed and will be available in the next BenchExec release soon.
