### ISSUE TITLE
Add parameter for tool directory to benchexec

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#593]
Currently, all tool-info modules search for the installation of the tool in the current directory or in the `PATH`. This means that if one wants to execute `benchexec` from somewhere outside of the tool directory, one needs to add the tool to `PATH`. This is mostly ok, but it is hard to discover for users and can be a little bit inconvenient. Furthermore, for tools that have their executable in a subdirectory of the tool directory (e.g., in `bin/`), one has to remember to add that subdirectory to `PATH`.

To simplify this, we could add a parameter `--tool-directory` and, if given, tell the tool-info module to look for the tool in that directory. This was not possible before but after #592 we can do this.

The logic would probably be that tool-info modules should only look in that directory if it is specified, and otherwise look in the current directory and `PATH` as they do currently.

@skanav: I think it was you who requested this feature once, right? Does this fit what you would like to have?

@MartinSpiessl: The tool-info module of MetaVal could maybe also benefit from this. Could you have a look at whether the above would help, and if not, tell us more about what you would need?

**Comment by skanav** [comment]
It doesn't affect me anymore. Now I change to the tool directory before using the tool info module.

**Comment by skanav** [comment]
My interest in this issue is renewed. I would like to have this. And yes, adding a parameter `--tool-directory` would do the trick.

**Comment by MartinSpiessl** [comment]
I do not need the command line parameter itself, as I am calling the wrapped modules programmatically. For that, it depends on how the additional parameter is handled internally. I added some comments to PR #602(which contains the  concrete implementation of this option) and sketched how MetaVal would make use of this.

In the end this will mean additional implementation effort for me since both variants need to be supported (since there could be tool-info modules still based on the old base class) and I do not actually gain anything from it.

It would however make the usability of BenchExec much nicer to have this command line option, so we should really add this!
