### ISSUE TITLE
Add a way to specify coefficients between 1 and 2 for the auxiliary lines in HTML tables

### ISSUE THREAD

**Issue by MartinSpiessl** [sosy-lab/benchexec#595]
Currently, when I look at the scatter plots in the HTML tables, I can select the coefficient c for the auxiliary lines to be one of:

    2,3,4,5,6,7,8,9,10,100,1000,...,100000000

Often when comparing two approaches it is a close call, but I cannot currently chose values between 1 and 2 for c.

Ideally there would be a way for the user to manually enter the value, but also some values between 1 and 2 would already be helpful.

As a side note, I doubt that 100000000 (10^8) will ever be useful to anyone. Even factor 1000 will probably not be that useful, I would focus more on the reasonable ranges. If some measure is off by that far, it is probably already quite obvious even without those auxiliary lines.

**Comment by PhilippWendler** [comment]
Let's add some values like 1.1, 1.2, 1.5 and remove everything beyond 10^6.

**Comment by MartinSpiessl** [comment]
That would be acceptable if adding a way to specify it manually is too much hassle.

**Comment by lachnerm** [comment]
> Let's add some values like 1.1, 1.2, 1.5 and remove everything beyond 10^6.

Alright. Are those 3 values between 1 and 2 sufficient or do we need more steps in between?

> Ideally there would be a way for the user to manually enter the value, but also some values between 1 and 2 would already be helpful.

Theoretically it's possible to allow the users to declare their own values. Some processing of the input would be necessary but it's not too much effort. We could directly put an input field next to the dropdown or a button that opens something like a modal with an input field. Both options don't really look that good in my opinion though - so if anyone has further suggestions how to implement the UI, I'd appreciate hearing them.
I guess it's also possible to somehow put this input field directly into the dropdown (e. g. at the very top, above the first option), however this isn't supported natively. I'd have to manually rebuild the dropdown, which could become quite hacky.

Alternatively we could use the `datalist` tag instead of a `select` tag. We could combine this together with an `input` field to allow users to write into the dropdown - and their input will be handled as the selection of the dropdown (if it fits the predefined pattern, i.e. only (decimal) numbers etc.). However, at the same time the input field will be functioning as some kind of "search field", so it will feel more like we offer some predefined suggestions instead of a list of options. If this is fine, I'd say it's the cleanest solution, at least regarding the UI. 
The mozilla documentation shows an example how this would work: https://developer.mozilla.org/de/docs/Web/HTML/Element/datalist

**Comment by PhilippWendler** [comment]
> > Let's add some values like 1.1, 1.2, 1.5 and remove everything beyond 10^6.
> 
> Alright. Are those 3 values between 1 and 2 sufficient or do we need more steps in between?

I would say they are sufficient.

> > Ideally there would be a way for the user to manually enter the value, but also some values between 1 and 2 would already be helpful.
> 
> Theoretically it's possible to allow the users to declare their own values. Some processing of the input would be necessary but it's not too much effort. We could directly put an input field next to the dropdown or a button that opens something like a modal with an input field.

I would say this is overkill and also distracts users too much. The feature is just a rarely used side feature.

> Alternatively we could use the `datalist` tag instead of a `select` tag.

My Firefox renders the Mozilla demo of `datalist` not really intuitively. If I focus the element, it looks like a regular input field. Only if I click on it again the list of suggestions is shown. This would mean that most users would not notice the easier-to-use predefined values. So I would argue against this.

What we would really need is a [combo box](https://en.wikipedia.org/wiki/Combo_box). Is this UI element available in HTML? If not, let's just keep the drop down I would say.

Any real data analysis should not be done my manually looking at how close the values are to a line, but by processing the data with R or something similar.

**Comment by lachnerm** [comment]
> > > Ideally there would be a way for the user to manually enter the value, but also some values between 1 and 2 would already be helpful.
> > 
> > 
> > Theoretically it's possible to allow the users to declare their own values. Some processing of the input would be necessary but it's not too much effort. We could directly put an input field next to the dropdown or a button that opens something like a modal with an input field.
> 
> I would say this is overkill and also distracts users too much. The feature is just a rarely used side feature.

Yes I agree, this would probably be too much.

> > Alternatively we could use the `datalist` tag instead of a `select` tag.
> 
> My Firefox renders the Mozilla demo of `datalist` not really intuitively. If I focus the element, it looks like a regular input field. Only if I click on it again the list of suggestions is shown. This would mean that most users would not notice the easier-to-use predefined values. So I would argue against this.

I see the problem, that could be difficult to find out for most users. Chrome renders it just fine with the suggestions showing immediately, but there doesn't seem to be a way to force this behavior upon Firefox too.

> What we would really need is a [combo box](https://en.wikipedia.org/wiki/Combo_box). Is this UI element available in HTML? 

Unfortunately there is no combo box element in native HTML. Actually the above solution with a `datalist` tag is the suggested way to implement a combo box in HTML. I've checked if there are any other solutions, but I didn't find anything that wouldn't make things way more complicated.

> If not, let's just keep the drop down I would say.

So we go with this solution and the additional steps between 1 and 2?

**Comment by PhilippWendler** [comment]
> > If not, let's just keep the drop down I would say.
> 
> So we go with this solution and the additional steps between 1 and 2?

Yes, please.
