### ISSUE TITLE
table-generator does not produce scores without expectedVerdict attribute

### ISSUE THREAD

**Issue by danieldietsch** [sosy-lab/benchexec#597]
I have a large number of benchexec results generated with benchexec < 3.0.

I want to generate tables comparing these with results generated by a newer benchexec (>= 3.0). 

``table-generator`` can merge these results if I manually remove the ``expectedVerdict`` attribute from the newer result XML files and manually expand the ``property`` attribute and add the ``propertyFile`` attribute to the older result XMLs. 

Unfortunately, now I do not see SVCOMP scores in the resulting tables. If I add the ``expectedVerdict`` to one run in the whole set, I get the scores back. 

Is there a better way to use table-generator to generate comparisons between old and new XML result files for SVCOMP?

**Comment by PhilippWendler** [comment]
You are talking about tasks with task-definition files, right?

Are the task-definition files accessible to table-generator? I.e., do the paths to the yaml files in the old results point to existing files (relative to the directory of the result files)? If both `propertyFile` and `expectedVerdict` are missing from the results file, table-generator should attempt to find this information in the task-definition file in order to support your use case.

What is the name of the property file, and is it one of the standard SV-COMP properties? Because the info about properties in the old result files is incomplete, table-generator can match the properties in old result files only if the names of the property files match.

**Comment by danieldietsch** [comment]
Yes, the benchmark definition talks about SV-COMP .yml files. Its in both cases the same benchmark and the same sv-benchmarks version. 

The .yml files are not accessible from the location where I run table-generator (because they are relative). 

The property file is ``svcomp/c/properties/valid-memsafety.prp``. 

But good to know; Ill try and replace all the relative paths with absolute ones.

It is still strange though: why is it enough to add the ``expectedVerdict`` to one run of thousands to get scores for all of them?

**Comment by PhilippWendler** [comment]
The paths in the result files (as all paths in files that BenchExec reads) need to be relative to the directory of the result file, not relative to the current directory. This is always the case after `benchexec` creates them, only if you move either the result files or the tasks this gets broken. And this was actually necessary already before BenchExec 3.0, the new version only improves this such that for new results the task-definition files need not be read anymore.

The expected verdict is not necessary for the score, `table-generator` will compute the correct score for each task depending on the property file. You can see this if you add a column called `score` to the table. However, computation of maximum achievable score depends on the expected verdict. The logic for showing the sum of scores in the last row of the summary tab is currently tied to the logic for computing and showing the maximum score, such that either both are shown or both are missing (in order to not show a meaningless score 0 for tables where scores do not make sense).

You should see a wrong max score if you only add one expected verdict, right?

**Comment by danieldietsch** [comment]
Ah yes, the max score is only 2. 

I mean, the relative paths are ok. Its just that I can replace them with absolute paths and it should work, because the result files are in a different place but on the same machine.

**Comment by danieldietsch** [comment]
Thank you for your help, when I use absolute paths everything works as expected.
