### ISSUE TITLE
Configuring benchexec with docker for macos

### ISSUE THREAD

**Issue by cajomferro** [sosy-lab/benchexec#611]
I have followed the benchexec installation instructions as described here: https://github.com/sosy-lab/benchexec/blob/master/doc/INSTALL.md#setting-up-cgroups-in-a-docker-container. My goal is to run benchexec on a docker container in a macOS.

After a lot of trial and error, I have managed to configure a proper docker file to run benchexec. I took notice of your advertisement:

> Note that you additionally need the --privileged flag for container mode. However, this gives your Docker container full root access to the host, so please also add the --cpa-drop=all flag, make sure to use this only with trusted images, and configure your Docker container such that everything in it is executed under a different user account, not as root. BenchExec is not designed to run as root and does not provide any safety guarantees regarding its container under this circumstances." 

However, I am not able to easily run benchexec process without being "root". The problem is that the required cgroup folders are automatically generated for each docker container and use the name of the container id. 

So for example, using the following configuration:

**Docker compose**
```yaml
version: "3"
services:
  main:
    build: ./
    command: bash
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cap_drop:
      - ALL
    privileged: true
```

**Dockerfile**

```
FROM ubuntu:latest

RUN apt-get update \
	&& apt-get install -y wget bc python3-yaml python3-pkg-resources python3.8 python3-coloredlogs libseccomp2 lxcfs \
	&& rm -rf /var/lib/apt/lists/*
RUN wget https://github.com/sosy-lab/benchexec/releases/download/3.2/benchexec_3.2-1_all.deb && dpkg -i ./benchexec_*.deb && rm benchexec_*.deb

RUN useradd -ms /bin/bash -g benchexec benchexec
WORKDIR /home/benchexec
USER benchexec

## Install local reqs
COPY --chown=benchexec src/benchmark-example-calculatepi.xml /home/benchexec
COPY --chown=benchexec src/calculatepi.py /home/benchexec
```

When I run the docker shell, my user is "benchexec". Then I run the following command:

```
benchexec benchmark-example-calculatepi.xml --no-container
```

And I get the following message:

```
...
Required cgroups are not available because of missing permissions.
Please configure your system in way to allow your user to use cgroups:
https://github.com/sosy-lab/benchexec/blob/master/doc/INSTALL.md#setting-up-cgroups-on-machines-without-systemd

As a temporary workaround, you can also run
"sudo chmod o+wt /sys/fs/cgroup/cpuset/docker/583877d5427745dcd63353a5fd53a3563b990f994cb1f2a2cb35083e9f99644a"
...
```

As you can see, the docker cgroup uses the docker container id. So I am not able to change these permissions on my dockerfile when running the container.

Right now, the workaround is to run the container as root, get the container id, change permissions, and then login as "benchexec". But this is very annoying...is there any better alternative? I couldn't managed to find useful documentation on how to configure cgroups to allow certain users to access groups. I recall that systemd is not being used because this is a docker container. For example, you mention [here](https://github.com/sosy-lab/benchexec/blob/master/doc/INSTALL.md#setting-up-cgroups-on-machines-without-systemd) that cgrules.conf could be used for that purpose. Do you have such an example? Thank you!

**Comment by PhilippWendler** [comment]
This is a good question.

We have this problem as well because we run our CI jobs in Docker containers, and there we do basically the same as you do, just automated with scripts and `sudo`: First, we create a user account, then we give this user access permission for each of the required cgroups and then we run the actual benchmarking under this user with `sudo`. You can see the relevant snippet in our [CI definition](https://github.com/sosy-lab/benchexec/blob/master/.gitlab-ci.yml#L26-L37), just ignore the remaining lines, which are not necessary for you. The used script is [this one](https://github.com/sosy-lab/benchexec/blob/master/test/for_each_of_my_cgroups.sh).

Does this help you?

In principle it would certainly also be possible to use some cgroups-management daemon like systemd or cgrulesngd, but I am not sure whether this is worth it. systemd is not common Docker containers AFAIK and probably effort to setup, and cgrulesngd can also be tricky (and I am not sure whether is still maintained).

There is, however, a long-term solution for you: after the switch to cgroups v2 (cf. #133) this problem should go away, because then finally cgroups properly support delegation and are namespace-aware. However, my latest info about cgroups v2 is that they do not fully support everything necessary yet and are not used by most distributions, so we did not yet stark working on support for them. And I also do not know whether Docker already supports them.

**Comment by PhilippWendler** [comment]
I just noticed that you used `--no-container` for `benchexec`. Note that this is not recommended, but if you use `--no-container` for `benchexec`, then you don't need `--privileged` for Docker.

On the other hand, depending on what you want to do, it could be easier for you to use `--privileged` for Docker plus container mode of `benchexec` (under a different user, of course). Because if you use container mode and you don't care about any resource limits and resource measurements, then you won't need cgroups.

**Comment by cajomferro** [comment]
Thank you for the quick replies! In my case, I don't really care about resource limits. I have this tool (much like a compiler) that I want to run several times for the same input (which is the source language to be compiled/analysed). I would like to have a simple benchmarking workflow where I can setup some compilation dependencies and then run the tool. I do care about the the measurement of the time it takes to compile the same input. Using `--privileged` is something I would like to avoid because it makes it more difficult for other users to run the benchmark (for example if they have a system where they don't have admin management). Is it possible somehow to use container mode without cgroups and without privileged?

**Comment by PhilippWendler** [comment]
Unfortunately, container mode is not possible in Docker containers without `--privileged` due to the way Docker configures its containers. There is nothing we can do about this, in fact BenchExec's own container properly allow nesting themselves, only Docker doesn't.
In other container runtimes than Docker the use of BenchExec could be possible depending on their configuration, though I do not have experience with any of them nor can I recommend one.

Note that container mode is not the same as cgroup usage, these are two separate features. If you want CPU-time measurements, you need cgroup access. However, you won't need container mode for that, and only container mode requires `--privileged`.

Of course, you could also just avoid the use Docker. AFAIK on MacOS Docker uses a VM with Linux anyway, so you could just start a Linux VM directly and use that. If you base your VM on Ubuntu (there are pre-built VM images available) and install the Debian package of BenchExec, the only remaining thing is to add your user account to the required group.

**Comment by PhilippWendler** [comment]
Did this help you or do you have further suggestions or questions? If there is nothing open I would close this issue.

**Comment by cajomferro** [comment]
Yes, I'm good! Thank you for your help. Btw, I've tried [Ubuntu multipass](https://multipass.run]) on macOS and it worked liked a charm. Successfully installed BenchExec on it!

**Comment by PhilippWendler** [comment]
Nice to hear, thanks for the response!
