### ISSUE TITLE
Improve HTML Tables for Edge or InternetExplorer

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/benchexec#637]
### Problem
When opening HTML tables with Edge or IE, the page stays just completely blank/white.
This is especially bad for SV-COMP tables.

### Possible Source of Evil
The problem could be a simple bug in the Javascript.
In IE once an error appeared: `Object doesn't support property or method 'flat'`, but did not look further into it.

### Wanted Solution
Either fix the bug (preferred)  
or at least print a proper warning, for example:   
`Edge and IE are not supported, these tables are optimized for Firefox and Chrome`.

### Even better Solution
The latest version of Edge is based on the Chrome rendering engine (or something like that?).
Maybe the tables could even work in Edge directly.

### Additional step for SV-COMP
The SV-COMP tables of 2019 work fine with Edge and IE (at least they show the table and clickable logfiles). 
The SV-COMP tables of 2020 just appear as a blank page.
Perhaps the SV-COMP organizers could manually update these tables afterwards.
That would greatly improve user experience.

**Comment by dbeyer** [comment]
>  Perhaps the SV-COMP organizers could manually update these tables afterwards.

Yes, this would be necessary.

**Comment by PhilippWendler** [comment]
@lachnerm Can you please check Chromium-based Edge to confirm that it works there?

Isn't non-Chromium Edge out of support soon and will be automatically replaced by Chromium-based Edge? So I guess we don't have to care about that. It's market share is already down to 0.5%.

It's similar for IE, it's global market share is about 1% and falling, among our target group certainly even less. Probably with IE you get blank pages for half of the web or so?

**Comment by lachnerm** [comment]
The table doesn't work  when using IE due to `create-react-app` not supporting those browsers by default:  

> By default, the generated project supports all modern browsers. Support for Internet Explorer 9, 10, and 11 requires polyfills. For a set of polyfills to support older browsers, use react-app-polyfill.

Probably between the SV-COMP tables of 2019 and 2020 there were some features added that aren't supported by IE and therefore the whole app just crashes.

`react-app-polyfill` is already installed in the project - maybe it is already used somewhere else or left over from some previous adjustments. So importing `react-app-polyfill/ie11` and `react-app-polyfill/stable` at the beginning of our `index.js` should suffice to view the tables in IE11. The first import is mandatory for IE and the second one makes newer language features - which we also use - work.
However, IE11 doesn't support the `onhashchange` event we use for updating the Quantile & Scatter Plot and therefore the dropdowns don't work. A workaround would be to use the `onhashchange` event instead when using IE - this seems to be stable. 
Also there are some bugs regarding the hidden columns and keeping them updated when switching between the tabs, but I haven't looked further into it so far.
I haven't found any other obvious bugs when using IE, but I can't guarantee that there are no others. Actually I think it's more likely that there are other problems due to IE not supporting newer features. And I'm sure that there will be further problems when adding new features in the future.

Regarding the really low percentage of people using IE (and as @PhilippWendler already stated, probably even less among those using the application), I wouldn't suggest fully supporting IE. I don't think it's worth the effort of always checking whether any added features are supported by a deprecated browser and add an alternative implementation if they aren't. Also the code can become quite confusing when having those alternatives everywhere.

Since fixing the app to at least show in IE is pretty cheap (importing the above mentioned 2 modules), I'd suggest fixing this bug so anyone using IE is not confronted with a blank page. In addition, we could add an error message as mentioned by @kfriedberger that the table is not optimized to work in IE and therefore some errors may occur. We could show this error message for example next to the menu-tabs or in an additional row just below the menu. We could make the basic functions of the plots work by adjusting the event for IE as mentioned above if you want to, but I don't think we should go any further.


> @lachnerm Can you please check Chromium-based Edge to confirm that it works there?
> 
I didn't run into any troubles when using the Chromium-based Edge, it works exactly the way it should. @kfriedberger Did you use the old version of Edge when testing the tables?

> Isn't non-Chromium Edge out of support soon and will be automatically replaced by Chromium-based Edge? So I guess we don't have to care about that. It's market share is already down to 0.5%.
> 
It seems that Windows has been updating all Edge installations for Windows 10 users with the Chromium-based one since June this year. It's not even possible to easily access or download the old version without some hacky workarounds anymore. So the problem should only occur for people who use Edge on a non-Windows OS and never update it or those who deliberately chose to keep the non-Chromium version. I don't think we need to take those groups into consideration, if there even are any who also use the tables.

**Comment by kfriedberger** [comment]
> I didn't run into any troubles when using the Chromium-based Edge, it works exactly the way it should. 
> @kfriedberger Did you use the old version of Edge when testing the tables?

Yes, I still have the old browser.
EdgeWithChrome is yet not installed for me.
My Windows machine is doing some updates in the background ("Please restart soon...").

I am totally fine with not supporting any browser that is not commonly used.
However, not showing any content (no tabs, no table, no text, no error message, just a white background) is bad user experience.
Perhaps it might not even need to be a real error message, but something like
`Please wait while the page is loaded. If this takes longer please consider using Firefox`.
That could even be displayed in all (other) browsers until the redering of the table starts and replaces the message.
And if rendering of the table does not start, the text remains visible.
