### ISSUE TITLE
required paths in tool info module

### ISSUE THREAD

**Issue by skanav** [sosy-lab/benchexec#698]
[REQUIRED_PATHS](https://github.com/sosy-lab/benchexec/blob/33029b5e38f18a5d13129d4969f8e30c219a2e18/benchexec/tools/template.py#L78)  is used in a tool info module to specify the paths that are necessary to run the tool. 
This variable is then used to compute the list of files to be transported to the cloud.

The default value of `REQUIRED_PATHS` is an `empty list`. This means that `benchexec` will only the `executable` is transferred if this variable is not explicitly defined in the tool info module of the tool.

I would propose to change the default behavior of `benchexec` to transfer the complete tool directory. This would also simplify tool info modules.

Now, `benchexec` does not know about the tool directory.  So we could do one of the following:
1. use `cwd` or `tool_directory` if explicitly specified
2. use the computed  `base_dir` of the `executable` in the function [`_program_files_from_executable`](https://github.com/sosy-lab/benchexec/blob/33029b5e38f18a5d13129d4969f8e30c219a2e18/benchexec/tools/template.py#L234)

**Comment by PhilippWendler** [comment]
What is the `base_dir` of an executable?

**Comment by skanav** [comment]
> What is the `base_dir` of an executable?

updated the comment

**Comment by MartinSpiessl** [comment]
> I would propose to change the default behavior of benchexec to transfer the complete tool directory. This would also simplify tool info modules.

This can backfire in case someone has a symlink to sv-benchmarks in the tool directory. Been there, done that, cannot recommend! Our cloud system fortunately complained and refused to accept such a large number of files (136k currently in sv-`benchmarks/c`).

> 1. use cwd or tool_directory if explicitly specified
> 2. use the computed base_dir of the executable in the function _program_files_from_executable

Same problem. Greedily declaring files as required might also be a security issue.

I personally don't want all my private test programs to end up in some cloud service just because a tool was lazy in defining what its required files are.

What about instead of changing the default behavior we add a flag that can be set by the user (at their own risk) and that will do what you want?

**Comment by PhilippWendler** [comment]
The `base_dir` you are referring to is simply the directory of the executable, unless the authors of the tool-info module specifically override `program_files`. However, this just overcomplicates things, instead of overriding `program_files`, it is much easier to simply set `REQUIRED_PATHS` accordingly. Your proposal 2 should be 'use `REQUIRED_PATHS = ["."]` as default'.

In general, I see the following problems:
- The current working directory is never a good choice, because that does not need to have any connection at all to the tool (e.g., if tool is taken from `PATH`) and could contain lots of other files.
- Using the directory for `--tool-directory` would introduce behavioral changes depending on whether this flag is present. Currently, there are no such changes except for where the tool is searched, but with this suggestion a different set of files would be assumed to be required depending on whether one uses `PATH` to tell BenchExec where the tool is or `--tool-directory`. This seems confusing and error-prone.

So this would leave only the directory of the executable as remaining option (e.g., use `REQUIRED_PATHS = ["."]` as default). However, I would say that this is also not worth the disadvantages for the following reasons:
- Explicitly specifying `REQUIRED_PATHS = ["."]` is easy and not really significant overhead.
- Changing the current default would go against the Pythonic spirit of "explicit is better than implicit".
- If `REQUIRED_PATHS = ["."]` is the default, `REQUIRED_PATHS` will still need to be set explicitly for those tools where this is not enough, e.g., because the executable is in a subdirectory. However, this will be harder to notice and thus be more error-prone than if we keep the current default, where any omission of `REQUIRED_PATHS` will be easy to spot and usually immediately noticed during execution.

**Comment by gernst** [comment]
I have heaps of stuff in all my tool directories, including .gitignore'd cruft, sometimes the entire sv-benchmarks, all the source files, build tool output, blabla, and I prefer to benchmark from the git root, so this is not a use-case for me (since you requested feedback).

**Comment by dbeyer** [comment]
> What about instead of changing the default behavior we add a flag that can be set by the user (at their own risk) and that will do what you want?

I would like this flag.  Probably not in benchexec but in benchmark.py.  I would like to provide a parameter that makes sure the whole working directory (or what I specify as parameter) with all its subdirectories is deployed.

**Comment by PhilippWendler** [comment]
I created an [issue](https://gitlab.com/sosy-lab/software/verifiercloud/-/issues/494) for the suggested parameter specifically.

Giving the responses to the current feature request, I will close this.

**Comment by dbeyer** [comment]
There is an anti-symmetry regarding REQUIRED_PATHS and benchmark.py.

We wanted to not have benchmark.py in the BenchExec repo because this is relevant only to users that have a VerifierCloud available.  But the REQUIRED_PATHS, which is also only relevant for users with VerifierCloud available, is spread all over the tool-info modules.

Consequence:
(1) Move benchmark.py into `contribs/` of the BenchExec repo, or
(2) get rid of REQUIRED_PATHS in BenchExec (no idea where to move it to).

I find it weird that to benchmark Korn, I have to checkout CPAchecker just to get benchmark.py.

If not moved to `contribs/` of the BenchExec repo, how about renaming
https://gitlab.com/sosy-lab/benchmarking/competition-scripts
to benchmarking-scripts or benchmarking-tools,
and then have benchmark.py there?

**Comment by PhilippWendler** [comment]
Let's discuss this internally because it is not relevant for the general BenchExec user's, only for people in our group.

**Comment by dbeyer** [comment]
Yes to "let's discuss elsewhere".
No to "it is not relevant for the general BenchExec users": I claim that general BenchExec users would have a happier live without `REQUIRED_PATHS`.

**Comment by PhilippWendler** [comment]
Note that BenchExec does not force anybody to specify `REQUIRED_PATHS`, it just *allows* developers to do so, which can be useful in certain cases like when combining BenchExec with job distribution systems like the example in `contrib/aws` does.

**Comment by MartinSpiessl** [comment]
Also we don't know whether someone out there is using BenchExec in their own cloud service and needs the `REQUIRED_PATHS` there as well.  I like the fact that I can find out which files a tool actually needs from the `REQUIRED_PATHS`.
