### ISSUE TITLE
Small issues with filters in HTML tables

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#704]
I encountered at least two slight problems with the current state of filters in HTML tables:
- When specifying a task-name filter via the table tab (not the filter overlay), this is not added to the URL.
- In tables with missing results (either empty cells or cells rendered as `--`), these seem to be always excluded if any filter is used. Even when selecting "Show all" in the filter drop down, such results are still excluded (even reflected by the count in the top right corner) and can be made visible only by using the trash-can icon. Selecting "Empty rows" in the filter always shows nothing.

**Comment by lachnerm** [comment]
> * When specifying a task-name filter via the table tab (not the filter overlay), this is not added to the URL.
> 
I've somewhat looked into this issue. It's possible and not really difficult to add the filter to the URL, but there is a compatibility problem regarding both "filtering systems".
Currently the filters for tasks are encoded in the URL like `id(values(task_name,prop))`. This stands for the filter of only showing tasks with `task_name` in their name **and** `prop` in their property identifier. Both values must be present. In case only one of the values is relevant, the other one can be left empty like in `id(values(,prop))`.
When using the task filtering of the table however, the filter doesn't work as a logical **and** any more, but as a logical **or**. Writing e.g. `test` into the input field will show all tasks that contain `test` in their task name **or** property. 

It would be possible to represent this **or** with something like `id(values(test,),values(,test))`, however a syntax like this is not supported currently and results in only the latter being applied. Also, the current UI of the filter card doesn't support differentiating between **and** and **or**. 
We could also use a different syntax that doesn't mix **and** and **or**, but handles them distinctly, e.g. `id_and(values(name,prop)),id_or(values(test))` or `id(values_and(name,prop),values_or(test))`. This would then currently not be compatible with the filter card too and could lead to unwanted interferences though.
One more thing I can think of would be dividing the filter field of the `Table` into two fields, one for the task name and one for the property - similar to how the filter card handles this. Then we could easily connect both filtering systems as they work the same way. We would lose the **or** functionality of the field though and I'm not sure if and how easily this can be done with the API we are using for the tables.
And lastly, since you were referring to the filter as 
> task-name filter
>
we could also remove the filtering for the `property` part and only filter the names themselves, in case the property is not really important here. Then we could always use the `id(values(task_name,))` syntax. When adding a property via the filter card menu to the filter though, this won't be visible in the filter of the table, so we would need to do something about that too.

**Comment by PhilippWendler** [comment]
Thanks for your thinking about this.

I would prefer to keep the filter working as it is. It is a little bit inconsistent, yes, but I guess it is convenient.

The fast way for task filtering is to just enter something in the filter row, and then we should search for this string in any part of the task id. Using a conjunction instead of a disjunction would not make sense, and searching only in the task name could be confusing because the column clearly contains the property, so users would expect it to be searched.

If users want to specify more precise task filters (with distinct search terms for task name and property, for example), they would instead need to open the filter overlay.

So the most common filters are quickly usable, and more powerful filters are still possible with a little bit more effort. If one of the two filter methods is used, the other one is unavailable (should be grayed out right now).

I don't think there is not enough space in the UI for adding more than one filter input in the filter row (there can be up to 3 items in the task id).

For adding the filter to the hash routing, I suggest something similar to your second suggestion: keep `id(values(task_name,prop))` working as is and add `id_any(values(...))` or `id(values_any(test))`.

What do you think?

**Comment by lachnerm** [comment]
> If one of the two filter methods is used, the other one is unavailable (should be grayed out right now).
> 
Currently the filtering via the table tab is indeed disabled when a filter via the filter menu is applied. However, this is not the case the other way around - it's possible to use the filtering menu when having a table-tab-filter applied. When adding a filter via the filter menu, the table-tab one will be removed though, so everything still works. I actually think this is fine as it is, what do you say? Just mentioning this because you said both filtering methods should disable the other.

> For adding the filter to the hash routing, I suggest something similar to your second suggestion: keep `id(values(task_name,prop))` working as is and add `id_any(values(...))` or `id(values_any(test))`.
> 
Alright, I'll work on a solution using this!

**Comment by PhilippWendler** [comment]
> When adding a filter via the filter menu, the table-tab one will be removed though, so everything still works. I actually think this is fine as it is, what do you say?

Yes, ok.

**Comment by PhilippWendler** [comment]
The bug with the filtering for empty cells was not addressed yet, @lachnerm could you please work on this?
Example table:
```
table-generator https://buildbot.sosy-lab.org/cpachecker/results/predicate-linear/01027.-r_integration-predicate-linear.2021-04-29_15-26-50.results.xml.bz2 https://buildbot.sosy-lab.org/cpachecker/results/predicate-linear/01029.-r_integration-predicate-linear.2021-04-29_19-17-30.results.xml.bz2
```

**Comment by lachnerm** [comment]
> ```
> table-generator https://buildbot.sosy-lab.org/cpachecker/results/predicate-linear/01027.-r_integration-predicate-linear.2021-04-29_15-26-50.results.xml.bz2 https://buildbot.sosy-lab.org/cpachecker/results/predicate-linear/01029.-r_integration-predicate-linear.2021-04-29_19-17-30.results.xml.bz2
> ```

I'm currently working on a solution. The problem is that there is no status value for the empty row, which makes it impossible for them to pass the filter test, as statuses are passed to the filtering function too when a category is selected. There is one thing that I'm not sure how to handle:
I think there is a rather intuitive solution for the table filtering, i.e. empty rows are shown by default and if "Empty rows" is selected, but hidden if any category or status filter is selected. This works fine so far.
However, when using the filter card, it is possible to filter for certain category/status combinations as well as multiple category/status criteria simultaneously. For the categories, it is still quite straightforward: the empty rows will be shown if "empty" is selected. But how do we handle empty cells with the status filtering? The equivalent to selecting "Show all" in the table would be having all statuses selected, so in this case, it would make sense to show the empty cells as well. But what should happen if one of the statuses is deselected? Should we remove the empty cell if any of the statuses is deselected? I can't think of a much better solution, but this would feel like (and also appear so when checking the number of tasks that are shown) the empty row is filtered out because it belongs to the deselected status, which is not quite correct either. What do you think would be the best approach?

**Comment by PhilippWendler** [comment]
> I think there is a rather intuitive solution for the table filtering, i.e. empty rows are shown by default and if "Empty rows" is selected, but hidden if any category or status filter is selected. This works fine so far.

Yes, this is as it should be. Filtering for empty rows is just like filtering for any of the other possibilities.

> However, when using the filter card, it is possible to filter for certain category/status combinations as well as multiple category/status criteria simultaneously. For the categories, it is still quite straightforward: the empty rows will be shown if "empty" is selected. But how do we handle empty cells with the status filtering? The equivalent to selecting "Show all" in the table would be having all statuses selected, so in this case, it would make sense to show the empty cells as well. But what should happen if one of the statuses is deselected? Should we remove the empty cell if any of the statuses is deselected? I can't think of a much better solution, but this would feel like (and also appear so when checking the number of tasks that are shown) the empty row is filtered out because it belongs to the deselected status, which is not quite correct either. What do you think would be the best approach?

I think the easiest way would be to show empty rows if and only if the checkbox "empty" is selected.

Furthermore, the checkbox "empty" should not be under "Category", just like "Empty rows" is not under "Category" in the filter drop down (I just noticed this bug now). Instead it should appear before "Category" and be named "Empty rows". (For the serialized filter form, we could keep it as is if this makes it easier, or add a new kind of status filters.)

And I just noticed that the order of category and status values in the filter card is different from the order in the filter drop down. This should also be made consistent.
