### ISSUE TITLE
benchexec tables cannot be filtered if result contains ":" 

### ISSUE THREAD

**Issue by danieldietsch** [sosy-lab/benchexec#727]
Ultimate has multiple results that contain the character `:`. The benchexec tables seem to have issues with filtering for these result types.

E.g., without filter: 
![image](https://user-images.githubusercontent.com/3883391/116114498-b291eb00-a6b9-11eb-95ed-aad588b69c54.png)

Dropdown:
![image](https://user-images.githubusercontent.com/3883391/116114563-c2a9ca80-a6b9-11eb-90a3-4160be7956e3.png)

Selecting "UNKNOWN: OverapproxCex"
![image](https://user-images.githubusercontent.com/3883391/116114615-cfc6b980-a6b9-11eb-9e77-db39fb23cd5d.png)

I would expect that I see all the runs with status "UNKNOWN: OverapproxCex", but instead, I see nothing.

**Comment by PhilippWendler** [comment]
Thanks for reporting this! I can confirm it, it is caused by the filter logic treating any filter value with a `:` in it as a numberic range filter:

https://github.com/sosy-lab/benchexec/blob/ccc5197058bd0faffaa1ef299a611fd54e62d8e0/benchexec/tablegenerator/react-table/src/utils/filters.js#L168

For fixing this we need to pass the column types down to this method, which I think is feasible.

@lachnerm Could you please work on this and add a unit test? Note that I already added such a case to the development data for debugging. Afterwards, please have a look at whether you find similar cases where the column type should be checked but is not. For example, the same method also does `if (name === "status") {`, but we don't want to hard-code column names (they can be changed).
