### ISSUE TITLE
Failed to configure container ... overlay mount for '/' failed

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#776]
On Ubuntu 18.04 with kernel 4.15.0-159 and on Ubuntu 20.04 with kernel 5.4.0-89-generic (and likely similarly recent versions) BenchExec fails by default with the error
```
CRITICAL - Failed to configure container: [Errno 22] Creating overlay mount for '/' failed: Invalid argument. Please use other directory modes, for example '--read-only-dir /'.
```
Avoiding the use of overlay for `/` (e.g., with `--read-only-dir /`) indeed makes it work. Overlay mode for other directories works.

According to the changelog ([here for 18.04](https://launchpad.net/ubuntu/bionic/+source/linux/+changelog)) the respective patch is very likely the one named "ovl: prevent private clone if bind mount is not allowed", which is originally [here](https://github.com/torvalds/linux/commit/427215d85e8d1476da1a86b8d67aceb485eb3631) and was backported to older kernels as well.

We have to investigate what exactly is the condition that makes it fail for `/` and lets it work for other directories, and then consider either reporting this as a regression or find a workaround. As the patch is a security fix (announcements from [Ubuntu](https://ubuntu.com/security/CVE-2021-3732), [Debian](https://security-tracker.debian.org/tracker/CVE-2021-3732)), we might need the latter.

**Comment by PhilippWendler** [comment]
For those affected by this issue, you can install [BenchExec 3.25](https://github.com/sosy-lab/benchexec/releases/tag/3.25) and [fuse-overlayfs](https://github.com/containers/fuse-overlayfs) 1.10 or newer (available for example in Ubuntu 24.04) and then the default directory works again without the need for `--read-only-dir /` or similar.

**Comment by younghojan** [comment]
Hi Philipp! Even though this issue has already been resolved, I realized that I never thoroughly investigated how it arose in the first place. I’m a bit confused. The commit [ovl: prevent private clone if bind mount is not allowed](https://github.com/torvalds/linux/commit/427215d85e8d1476da1a86b8d67aceb485eb3631) prohibits calling `clone_private_mount()` on a mount that contains a locked submount. Why does this lead to all mounts containing non-leaf mount points being treated as `lowerdir` by the overlay mount?

**Comment by PhilippWendler** [comment]
Hi @younghojan Nice to hear from you! Unfortunately I don't know more about the kernel logic here. It was just a guess that this commit is the responsible one, as it seemed most plausible. But maybe I overlooked another commit. I would, however, be very interested in knowing more about this, if you happen to find more information!

**Comment by younghojan** [comment]
Yes! I believe I have found a possible underlying cause. 

```
mkdir /tmp/test /tmp/test/upper /tmp/test/work
unshare -m -U -r mount -t overlay none / -o lowerdir=/,upperdir=/tmp/test/upper,workdir=/tmp/test/work
```

In the operation above, we create a new **mount** namespace and a new **user** namespace. Then, we attempt to perform an overlay mount within the new namespace, where the lowerdir is the root directory of the entire system.

When a process requests a new mount namespace via the `clone()` or `unshare()` syscall, the [`copy_mnt_ns`](https://github.com/torvalds/linux/blob/3f31a806a62e44f7498e2d17719c03f816553f11/fs/namespace.c#L4309) function is called. When a new **user** namespace is created, the condition [`if (user_ns != ns->user_ns)`](https://github.com/torvalds/linux/blob/3f31a806a62e44f7498e2d17719c03f816553f11/fs/namespace.c#L4345) within `copy_mnt_ns` becomes true. Consequently, `lock_mnt_tree(new)` is called, which sets all the nodes in the entire new mount tree to a locked state.

Subsequently, OverlayFS calls the [`ovl_get_layers function`](https://github.com/torvalds/linux/blob/3f31a806a62e44f7498e2d17719c03f816553f11/fs/overlayfs/super.c#L995) to create a private copy of each mount point within the **lowerdir**. This is achieved through `clone_private_mount`. Since these mount points were previously locked, the `clone_private_mount operation` will fail.

**Comment by PhilippWendler** [comment]
Wow, impressive investigation! Thank you!

Is there an indication that we can find a workaround?

**Comment by PhilippWendler** [comment]
Yes, it is, and it is really useful. But of course a solution without external dependencies would also be nice. Thanks anyway for the investigation, it is always good to know what the root cause is!
