### ISSUE TITLE
Improvement of warning message

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/benchexec#783]
If I select a task set with parameter `-t`, and a run definition in the benchmark definition XML file does not contain that task set, then I receive the following message:
```
2021-11-07 11:34:49 - WARNING - The selected tasks "ReachSafety-ControlFlow" are not present in the input file, skipping them.
```
For me, `are not present in the input file` is not appropriate, because the task set is definitely present in the [input file](https://gitlab.com/sosy-lab/sv-comp/bench-defs/-/blob/main/benchmark-defs/cpachecker.xml) (or it is unclear what `input file` refers to).
Perhaps change to `are not contained in run definition "SV-COMP22_valid-memcleanup"`?

My example:
```
../../benchexec/bin/benchexec -t ReachSafety-ControlFlow ../../benchmark-defs/cpachecker.xml
```
where `cpachecker.xml` is the file https://gitlab.com/sosy-lab/sv-comp/bench-defs/-/blob/main/benchmark-defs/cpachecker.xml

**Comment by dbeyer** [comment]
Perhaps orthogonal: Interestingly, the warning is shown even if I add the run definition as parameter with `-r SV-COMP22_unreach-call`.

**Comment by PhilippWendler** [comment]
"input file" here refers to the file given to benchexec as input, i.e., the benchmark definition. I have improved the wording and added the name of the run definition for clarity.

Only printing the warning for run collections that are actually selected would in theory be possible, but too tedious / risky this benefit, because for this we would have to no longer create the full data model of everything that is in the benchmark definition if we are to use only a part of it, but it is hard to judge whether there is anything else in BenchExec that has the assumption that the data model is fully complete.
