### ISSUE TITLE
Round numbers in tables to significant digits

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#79]
All numeric measurement results shown in the HTML tables should be rounded to a given number of significant digits instead of to a fixed number of decimal places, e.g., `12.3` and `1.23` instead of `12.344` and `1.234`.

The numbers should stay aligned at the decimal point. This could be done by computing the maximum width of all numbers in a column and filling the remaining places of each numbers with white space. The characters `&#x2007;` (FIGURE SPACE) and `&#x2008;` (PUNCTUATION SPACE) are the correct whitespace characters for same-width replacements of digits and dots, respectively.

For example, the value `1234.567` could become `1230&#x2008;&#x2007;&#x2007;&#x2007;` (`1230    `).

HTML | Shown as
---------|-------------
`1230&#x2008;&#x2007;&#x2007;&#x2007;` | `1230    `
`&#x2007;123&#x2008;&#x2007;&#x2007;&#x2007;` | ` 123    `
`&#x2007;&#x2007;12.3&#x2007;&#x2007;` | `  12.3  `
`&#x2007;&#x2007;&#x2007;1.23&#x2007;` | `   1.23 `
`&#x2007;&#x2007;&#x2007;&#x2007;.123` | `    .123`

**Comment by dbeyer** [comment]
This should actually be split into two independent features: 
(a) adhere to significant digits (i.e., we must not display digits that have no significance) and
(b) nicely align the numbers at the decimal point in the table columns.

The correct number of significant digits should be provided by the measurement engineer
(in the XML table definition).

I have implemented a preliminary version of these two features in functions 
- format_number (reduce to significant digits) and
- format_number_align (alignment)
in util.py.

The perfect adjustment is only possible with the counting mentioned by Philipp.
But instead of the "maximum width" we need the "maximum number of digits after the decimal point",
for a correct alignment that works for all situations.

The current implementation works well for values larger than 0.1
(i.e., when the max number of digits after the decimal point coincides with the number of significant digits).

**Comment by PhilippWendler** [comment]
The same assignment also needs to be done for the statistics lines at the bottom of the table.

**Comment by PhilippWendler** [comment]
There is currently something wrong with at least some results, I have cases where values between 0 and 1 get rounded incorrectly to `0`. This is visible for example in the test case `test_multi_table_xml_with_columns` in column `SMT time (s)`.

Furthermore, it seems that statistics get computed only for the first set of results in a table (visible among others in the same test case).

**Comment by leostrakosch** [comment]
The two stated bugs should be fixed by commits 9bddbd8 and 769e9ea, sorry about them.

Another issue: How should the format of value 0 look like?
E.g.: Number of significant digits = 3, value = 0.0000
Should we display 0.00 or 0.0000?

**Comment by PhilippWendler** [comment]
Good question. `0.00` would look more natural in general, while `.000` would look more like the values nearby. There is still a mismatch with very small values like `.00123` anyway though, thus I think we can go with `0.00`.

**Comment by PhilippWendler** [comment]
The rounding is almost perfect now, except values like `0.070` get rounded to `.07` instead of `0.070`.

Could you please add some unit tests for `format_number`/`format_value`?

**Comment by PhilippWendler** [comment]
For columns of format `count`, the average and stdev values in the summary tooltips of the footer now have too many digits. I think these can be rounded to 1 or 2 decimal places. If the user gave a number of significant digits for this column, this should be applied here as well, of course (just like it is already done for `measure` columns).

**Comment by PhilippWendler** [comment]
There also seem to be too many spaces on the right now for columns with small values, e.g. again in test case `test_multi_table_xml_with_columns` in column `SMT time (s)`.

**Comment by PhilippWendler** [comment]
Thanks @leostrakosch, I could not find any remaining problem, thus I am closing this. Please still write some unit tests, and if you think the current code is worth to be refactored, feel free to do so.
