### ISSUE TITLE
Custom column definition in benchmark XML vs table XML

### ISSUE THREAD

**Issue by sim642** [sosy-lab/benchexec#794]
Almost all of the documentation about custom columns is about defining them in the table XML, except there's one example of a benchmark XML, where this is done instead of the table XML:
https://github.com/sosy-lab/benchexec/blob/0e0f79cf8d7cc52bf7e7c9a4c622f8d070c855d7/doc/benchmark.xml#L48-L51

I noticed this being used for CPAchecker's SV-COMP 2022 bench-defs (https://gitlab.com/sosy-lab/sv-comp/bench-defs/-/blob/a39fca228c17c1b022ff11ccdfc3fe09b611cdab/benchmark-defs/cpachecker.xml#L174-176), but couldn't find any information about doing it that way.

Looking at the XML schemas and Python implementations, it also seems like the benchmark XML way is much more limited.
What's the relationship between the two or are there any other differences? Is it some deprecated way of using custom columns or is it still implemented because it has some advantage that the table XML does not?

**Comment by PhilippWendler** [comment]
Right. We mostly document only the table-generator feature for this because there is little reason to already do this with benchexec. The only advantage of the latter is that the data will already be in the results XML if benchexec extracts it, so it will be added automatically to the tables (no need to write a table-definition XML) and table generation can be faster. For these two reasons we also did not decide to deprecate it, though.

However, the feature should work exactly the same way, no matter whether it is used in benchmark definitions or table definitions. Could you please tell me where you thought it would differ? I would like to double-check.

I hope this clears up your questions?

**Comment by sim642** [comment]
The difference I saw was that the table-generator columns have lots of properties:
https://github.com/sosy-lab/benchexec/blob/082257483e2f9bf4766edeb08952e7ef1aaf332b/benchexec/tablegenerator/columns.py#L121-L151
whereas the benchexec ones have much fewer:
https://github.com/sosy-lab/benchexec/blob/38310eeb567c474cf4de59456d1faca23e3f3dc3/benchexec/model.py#L1181-L1190

**Comment by PhilippWendler** [comment]
Ah right, I forgot these.

There are two features that `<column>` in table definitions has: Extracting values from tool outputs, and formatting values, e.g., by conversion to a different unit.
The `<column>` in benchmark definitions only supports the former (with the exception of rounding, but only for historic reasons).

Btw., no need to look into the source, the docs are here:

https://github.com/sosy-lab/benchexec/blob/0e0f79cf8d7cc52bf7e7c9a4c622f8d070c855d7/doc/table-generator.xml#L15-L35

https://github.com/sosy-lab/benchexec/blob/0e0f79cf8d7cc52bf7e7c9a4c622f8d070c855d7/doc/benchmark.xml#L48-L51
