### ISSUE TITLE
Handle special characters in filters of HTML tables

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#806]
Not all special characters are handled correctly if a user enters them as a filter for task ids or textual columns because of missing escaping. Some of them just do not work, some actually break the parsing of the URL.

Some characters are actually handled differently depending on whether they are entered on the table tab or in the filter overlay, but not sure whether either of them is working.

We should check and handle at least the following characters, and also add tests for them:
- `?`
- `#`
- `&`
- `=`
- `(`
- `)`
- `,`
- `*`

**Comment by PhilippWendler** [comment]
Having `_` in a column name breaks filtering for that column because internally we split various times on `_`.

**Comment by JawHawk** [comment]
https://github.com/sosy-lab/benchexec/assets/86140365/0c686122-f119-4622-b801-051fbee76e57

@PhilippWendler  `&` is causing a breaking error in setting and parsing of url. I checked the other characters but didn't find any odd working. Also can you provide an example for `_` in column name that breaks filtering because I tried but couldn't recreate it. 
**I am interested in solving this issue, can you please assign it to me ?**

**Comment by PhilippWendler** [comment]
Sure, would be great!

Just make sure to coordinate with #1006 if you need to change related parts of the code (not sure).

For `_` it is my suspicion that it may break stuff due to the logic in `decodeFilter` (cf. #1005). Maybe I am wrong, but it would still be good to have tests for it together with all the other special characters, even if they already work.

**Comment by JawHawk** [comment]
Error occurs when `&` is used because we are currently splitting by `search.split("&")`. This can be solved by using `encodeURIComponent()` so it converts `&` to `%26` and `decodeURIComponent()` can be used to get the value back. Is this okay ?

Also why are we using url to store the filter and other values ? Is there any specific reason ? I think using localstorage or sessionstorage will also satisfy the case and will be much easier to access.

**Comment by PhilippWendler** [comment]
Yes, URI encoding seems to be the intuitive choice.

Using the URL as state store is by design, because we want to make it possible for people to create links that directly open a specific view of the table. This is extremely useful for many users of BenchExec.
