### ISSUE TITLE
No documentation on table-generator's CSV layout

### ISSUE THREAD

**Issue by MartinSpiessl** [sosy-lab/benchexec#819]
Currently I cannot find any documentation about how the CSV files are structured that are output by `table-generator`.  
I assumed this would be documented in https://github.com/sosy-lab/benchexec/blob/main/doc/table-generator.md, but the only mention of the CSV is in the first paragraph of that markdown document, without any further explanation down the road.

(The reason why I search for this is that I want a simple and documented way to read in the experimental data and run some queries on it. Ideally benchexec could provide some documented way to access this data structure, e.g. parse it into a python dictionary that makes accessing and manipulating the data more fun.
I know there is `tablegenerator.parse_results_file(result_file)`, but one has to fiddle around to understand how the created data is structured here. Also this is not public API. Still I will probably now go for `tablegenerator.parse_result_file` as this is closest to what I actually need.)

**Comment by PhilippWendler** [comment]
Documentation was added.

Currently we do not provide an official API for working with result data because properly designing such an API in a way that enables interesting use cases while staying usable and understandable is a lot of effort, especially because we would need to commit to keep it stable in order to make it useful. Furthermore, designing such an API is easier after one already has seen a few use cases instead of just thinking about what could be relevant. So in principle we are interested in use-case stories (but not in an issue about CSV tables, though).

Of course, also feel free to add contributions to `table-generator` or add some useful scripts to the `contrib/` directory!

**Comment by MartinSpiessl** [comment]
Thanks :smile: !
