### ISSUE TITLE
Output files should be made world-readable

### ISSUE THREAD

**Issue by cyrille-artho** [sosy-lab/benchexec#824]
For our P4 extension of benchexec (in contrib), we need to run all tests as root, because a non-root user cannot create virtual network interfaces. At the end of the run, the results are not readable by other user accounts, which means that currently, the evaluation scripts that produce the plots and HTML tables also have to be run as root.
If the output of benchexec is written with permission 0644, then this problem does not occur. I do not see a downside in making all files world-readable.

**Comment by PhilippWendler** [comment]
I don't think we do anything special regarding permissions, so I would expect the current umask setting to be applied automatically. And in fact, the result files here on my system are world-readable (which matches my umask).

Maybe your umask is more restrictive than 0002 while executing BenchExec? Then you could change that.

But in your scenario, the way I would do it would be to chown the result files afterwards to the desired user, because at some point one will anyway want to the delete them or move them, and the files being owned by root but world-readable would not be enough.

**Comment by PhilippWendler** [comment]
So far there is no indication that BenchExec does not just honor the umask, so I think there is nothing to do here and will close this. Please comment/reopen if there is indeed some undesired behavior.
