### ISSUE TITLE
Support for milliseconds when setting time limit

### ISSUE THREAD

**Issue by maxkudosh** [sosy-lab/benchexec#836]
Hi,

I'm using RunExec in one of my projects when I need to control and limit resources for the executing code. There are cases when I need to provide non-integer time limits. But currently RunExec doesn't support time limits less than a second or non-integer numbers.

I'd like to ask if there are plans to add support for such time units? If no, may I request to add such units? Or would the PR adding support of such units be accepted?

Best regards,
Max

**Comment by PhilippWendler** [comment]
We have no plans in this regard, and I wonder how effective it would be. Unfortunately, we cannot tell the kernel our time limit, but we have to sleep until the limit elapses and then terminate the processes. And currently we make sure to always even sleep for one second more in order to wake up as rarely as possible and avoid falling into busy-waiting behavior. So changing to non-integer time limits would not change when the processes are terminated, only what counts as timeout in the result. Is this what you need? I think this could be added relatively easily.

If you really need RunExec to terminate processes milliseconds after the time limit, this would be more difficult to achieve (and on a non-RT OS, not in general possible to achieve with guarantee).

**Comment by maxkudosh** [comment]
> So changing to non-integer time limits would not change when the processes are terminated, only what counts as timeout in the result. Is this what you need?

Yes, that would work. In my specific case, it's more important to use non-integer timeouts, than to make the execution time exactly equal to the specified limit.

In other words, it would work for me if:
- I'd be able to set non-integer or milliseconds timit limit;
- RunExec would use its own strategy of sleeping / waking up to verify the limit and terminate the process if needed (with a minimum one second interval, as you described);
- RunExec would report timeout if the time limit was exceeded, even if the execution time eventually was less than the sleep period, or there was a termination some time after the time limit was exceeded, for example.

**Comment by PhilippWendler** [comment]
Hm, actually with regards to your last point (I also had not described this precisely in my previous comment): RunExec currently does not actually return whether a time limit was exceeded at all. Only BenchExec does that. What RunExec does is that it returns the `terminationreason`, but this value describes only whether and why the processes were forcefully terminated. In the case that the processes terminate after the time limit but before time-limit enforcement by RunExec, `terminationreason` will be empty (this also matches how `terminationreason` is [documented](https://github.com/sosy-lab/benchexec/blob/main/doc/run-results.md)). BenchExec on the other hand computes the `status` value, and that will be `TIMEOUT` if the time limit was exceeded.

So, if you are using only RunExec (and not BenchExec), we have two possibilities for your feature request:
- We implement fractional time limits in RunExec and add a new field to its result that indicates whether a limit was exceeded, independently of `terminationreason`.
- You round up your time limit for RunExec and after the run check the returned `cputime` value against your actual time limit.

I tend to see RunExec more as a low-level tool and put the advanced interpretation of results in BenchExec. Thus I would slightly prefer the latter option, and it should be relatively little effort for you, right? However, if for some reason this is inconvenient or problematic, we can reconsider.

**Comment by maxkudosh** [comment]
So we do use simply RunExec, it is more lightweight and convenient in our case when we execute different code snippets in different languages on the fly and limit / measure some metrics for it (memory, time). It would be harder to use BenchExec since it accepts XML files for input which we'd have to generate (there are probably more complications, I'm not sure of them all).

We'd prefer RunExec returning the time limit status field, because that's something we'd expect from such tools, even as low level as RunExec. And it actually returns such a status field now, the only problem is that non-integer time limit support would conflict with existing status field due to the implementation detail of time-limiting strategy.

Of course, if the first option won't be possible, we could follow the second option. As far as I understand we'll be able to do it right away, because `cputime` and `walltime` result fields already report non-integer numbers.

**Comment by PhilippWendler** [comment]
> So we do use simply RunExec, it is more lightweight and convenient in our case when we execute different code snippets in different languages on the fly and limit / measure some metrics for it (memory, time). It would be harder to use BenchExec since it accepts XML files for input which we'd have to generate (there are probably more complications, I'm not sure of them all).

Sure, both tools really serve different use cases and it does not make sense to use BenchExec when you need RunExec.

> And it actually returns such a status field now, the only problem is that non-integer time limit support would conflict with existing status field due to the implementation detail of time-limiting strategy.

Be careful: RunExec does not return such a status field right now. `terminationreason` does not indicate whether a limit was violated, it only indicates why the tool was terminated forcefully (*if* it was terminated forcefully). But even with integer time limits there is a chance that the tool terminates itself after the time limit before gets terminated forcefully.

> We'd prefer RunExec returning the time limit status field, because that's something we'd expect from such tools, even as low level as RunExec.

I understand. The problem is that RunExec can not just return the same status field as BenchExec, because it simply does not have enough information (part of BenchExec's status field is parsed from the tool output). So if we do this, we would have two different status fields, with the one from BenchExec containing a superset of the information that the one from RunExec has. And on top of this there would still be the `terminationreason` field with yet different semantics. This is doable but could easily end up being confusing, so it needs a lot of thought before being implemented. Unfortunately, I am currently busy with other features for BenchExec, so I cannot work on this soon.

> Of course, if the first option won't be possible, we could follow the second option. As far as I understand we'll be able to do it right away, because `cputime` and `walltime` result fields already report non-integer numbers.

Exactly.

**Comment by maxkudosh** [comment]
Okay, understood. Let me know if one day that'll be added. For now we'll stick with the second option.
