### ISSUE TITLE
tablegenerator: support both table definition and raw result file(s) as arguments

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/benchexec#96]
Hi,

Re-using table definitions across different benchexec runs is slightly annoying, because the produced filename keeps changing (post-fixed with the date), and it is not user-friendly to have to edit the table definition each way.
Would be nice if I could instead specify logfile locations using an additional command line argument to table-generator.

**Comment by PhilippWendler** [comment]
You can use wildcards in the table definition file (like almost everywhere in BenchExec), you do not need to specify precise file names.

Your proposal I do not understand. Why should log files be specified at the command line? The log files are always resolved relative to the path to the XML result file.

Please give a concrete example command line of what you are proposing, and explain what would be its semantics.

**Comment by cheshire** [comment]
1. My mistake, I've meant output XML file, not logfile path.
2. I can use wildcards, but if I have many XML files in that directory under the same name, wouldn't the table-generator run on all of them? That is not something desirable.
3. Just `table-generator output.xml -x table_definition.xml` would do.

**Comment by PhilippWendler** [comment]
2. You can of course use arbitrary wildcards, like `*2015-11-18*.xml` to get only files from today, for example. Or you group the result files into appropriate directories.
3. What would be the semantics of this? What is the difference to `table-generator output.xml` and to `table-generator -x table_definition.xml`?

**Comment by cheshire** [comment]
1.

> You can of course use arbitrary wildcards

But then I would need to change the file with the table definition!
I would like to get it working while using the _same_ table definition for multiple files.

2. 

> table-generator output.xml

Process "output.xml" using no custom table definition.

> table-generator -x table_definition.xml

Process the table definition using the specified results file.

>  table-generator output.xml -x table_definition.xml

Process output.xml using table_definition.xml.

**Comment by PhilippWendler** [comment]
>> table-generator output.xml -x table_definition.xml
> 
> Process output.xml using table_definition.xml.

That's the point I still do not understand. `table_definition.xml` is a declarative description of how the final table should look like, not a set of statements that can be used to "process" an input file. Please explain what this command should actually do.

**Comment by kfriedberger** [comment]
> table-generator output.xml -x table_definition.xml´

* output.xml: 
    provides results with arbitrary columns {a,b,c,d,e}

* table_definition.xml: 
    provides a specification, which columns should be used and in which order, e.g. {a,e,b}.

Currently the specification of columns is coupled with the result itself.
This issue/step would make both parts independent from each other.

**Comment by PhilippWendler** [comment]
Ah, so you want to take the result files from command line and only the `<column>` tags from the table-definition file. Now I understand.

The reason this is coupled is because the table-definition file is not just a list of result files and a list of columns, it supports more than that. You can for example specify a different set of columns for each result file, or combine result files using `<union>`. All this wouldn't be possible with the proposed command-line syntax.

But if you think this is worth it, you could implement it of course. I would prefer if this syntax is accepted only if the table-definition file does not contain anything else than `<column>` tags, to avoid the confusion about which of the result files will get used if they are specified both in the XML and on command line.

What would the output name would be by default? Probably both the name of the table-definition file and the name of the result file(s) do not make sense, so we fall back to the default `result.timestamp.table.html` unless the user overrides this explicitly?

**Comment by cheshire** [comment]
@kfriedberger 
Thank you!

@PhilippWendler 

>  I would prefer if this syntax is accepted only if the table-definition file does not contain anything else than <column> tags

Yes.

> so we fall back to the default result.timestamp.table.html unless the user overrides this explicitly?

Yes.

> But if you think this is worth it, you could implement it of course

Yes, I'll take a look, shouldn't be too hard. I find this issue quite annoying, as it stops me from having a reusable, benchmark-independent table definition file with detailed statistics i care about.
